### ISSUE TITLE
kick with bungee

### ISSUE THREAD

**Issue by PhanaticD** [sgtcaze/NametagEdit#131]
```
java.lang.IllegalArgumentException: Team NTE-15 already exists in this scoreboard
    at com.google.common.base.Preconditions.checkArgument(Preconditions.java:145)
    at net.md_5.bungee.api.score.Scoreboard.addTeam(Scoreboard.java:68)
    at net.md_5.bungee.connection.DownstreamBridge.handle(DownstreamBridge.java:205)
    at net.md_5.bungee.protocol.packet.Team.handle(Team.java:102)
    at net.md_5.bungee.netty.HandlerBoss.channelRead(HandlerBoss.java:77)
    at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:373)
    at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:359)
    at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:351)
    at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:102)
    at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:373)
    at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:359)
    at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:351)
    at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:102)
    at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:373)
    at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:359)
    at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:351)
    at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:293)
    at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:280)
    at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:396)
    at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:248)
    at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:373)
    at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:359)
    at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:351)
    at io.netty.handler.timeout.IdleStateHandler.channelRead(IdleStateHandler.java:266)
    at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:373)
    at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:359)
    at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:351)
    at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1334)
    at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:373)
    at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:359)
    at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:926)
    at io.netty.channel.epoll.AbstractEpollStreamChannel$EpollStreamUnsafe.epollInReady(AbstractEpollStreamChannel.java:1018)
    at io.netty.channel.epoll.EpollEventLoop.processReady(EpollEventLoop.java:402)
    at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:307)
    at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:873)
    at java.lang.Thread.run(Thread.java:745)
02:14:05 [INFO] [JCC76] disconnected with: The server you were previously on went down, you have been connected to the lobby
```

**Comment by sgtcaze** [comment]
Do you utilize the "SortPriority" feature? Please note, "SortPriority" is not the same as "Order".

**Comment by PhanaticD** [comment]
I am not sure what you mean, I dont see any config option for that

**Comment by sgtcaze** [comment]
SortPriority is a feature that allows you to organize how groups/players appear in the tab list.
e.g. You want all players with an Admin tag to display first, down to your most basic rank last.

This error pops up when that feature is incorrectly configured, I believe. I've only seen it one other time.

**Comment by PhanaticD** [comment]
i dont even see that anywhere in my config

**Comment by sgtcaze** [comment]
Perhaps you are using an out of date NametagEdit. This was added in v4.0.3 of NametagEdit:
https://github.com/sgtcaze/NametagEdit/blob/master/src/main/resources/config.yml#L18

This was added to test a theory with another user's server (collision property).

**Comment by PhanaticD** [comment]
no, sortpriority

**Comment by sgtcaze** [comment]
Whoops, wrong issue.

Checkout the documentation here: https://github.com/sgtcaze/NametagEdit/blob/master/documentation/Configuration.creole

If no default SortPriority is given, it will use the default NametagEdit team-naming.
https://github.com/sgtcaze/NametagEdit/blob/master/src/main/resources/groups.yml#L6

Here's what I think is going on - it's related to how nametagedit generates fake team names. All IDs start at 1, and for each new fake team, the ID is incremented. You likely have multiple servers using NametagEdit which increment to the same ID values - which causes a clash with duplicate team names. My guess is the player scoreboards/teams are not being cleared when they switch servers, and bungee complains.

Again it's a rare issue, however I've been searching through Bungee's API and noticed they definitely intercept those packets, and handle a lot of storage. I noticed this when taking profiles of Bungees in the past.

**Comment by PhanaticD** [comment]
related: http://pastebin.com/raw/3NSxeXAw

**Comment by PhanaticD** [comment]
http://pastebin.com/c1UMRvXG
^this was the first occurrence of the error, then after that it happens for every new login until a server restart

**Comment by PhanaticD** [comment]
I added different sortpriority numbers for my hubs nametagedit, so they wouldnt have the same number as other servers, but it still happens
