### ISSUE TITLE
Problem with Logblock

### ISSUE THREAD

**Issue by Greenman1805** [sgtcaze/NametagEdit#2]
The error is still appearing in the new version:

[14:52:55 INFO]: [LogBlock] Loading LogBlock v1.10.0-dev-SNAPSHOT (build #269)
[14:52:55 INFO]: [LogBlock] Connecting to ni101661_2sql1@jdbc:mysql://vweb18.nitrado.net:3306/ni101661_2sql1...
[14:52:56 WARN]: [Server thread] ERROR com.zaxxer.hikari.HikariDataSource - when specifying jdbcUrl, driverClassName must also be specified
[14:52:56 ERROR]: [LogBlock] Error while fetching connection:
java.lang.IllegalStateException: when specifying jdbcUrl, driverClassName must also be specified
        at com.zaxxer.hikari.HikariConfig.validate(HikariConfig.java:672) ~[NametagEdit.jar:?]
        at com.zaxxer.hikari.HikariDataSource.getConnection(HikariDataSource.java:102) ~[NametagEdit.jar:?]
        at de.diddiz.util.MySQLConnectionPool.getConnection(MySQLConnectionPool.java:38) ~[LogBlock.jar:?]
        at de.diddiz.LogBlock.LogBlock.getConnection(LogBlock.java:263) [LogBlock.jar:?]
        at de.diddiz.LogBlock.LogBlock.onLoad(LogBlock.java:63) [LogBlock.jar:?]
        at org.bukkit.craftbukkit.v1_8_R3.CraftServer.loadPlugins(CraftServer.java:297) [spigot.jar:git-Spigot-db6de12-3f3c65f]
        at net.minecraft.server.v1_8_R3.DedicatedServer.init(DedicatedServer.java:198) [spigot.jar:git-Spigot-db6de12-3f3c65f]
        at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:525) [spigot.jar:git-Spigot-db6de12-3f3c65f]
        at java.lang.Thread.run(Thread.java:745) [?:1.8.0_60]

**Comment by sgtcaze** [comment]
```
Error while fetching connection:
java.lang.IllegalStateException: when specifying jdbcUrl, driverClassName must also be specified
```

When you connect to your database your driver doesn't look to be specified. This is not an issue with NametagEdit (or at least the error you provided does not relate to NametagEdit)

Feel free to send a screenshot of your database structure so we can make sure NametagEdit is generating tables properly.

**Comment by Greenman1805** [comment]
The problem is that I don't use MySQL for NametagEdit. And Logblock works well with my database but when I install NametagEdit it gives this error.

**Comment by sgtcaze** [comment]
Send me your config.yml for NametagEdit and a screenshot of your database structure.

**Comment by Greenman1805** [comment]
My config.yml:
http://pastebin.com/JGbAx9SS
![database](https://cloud.githubusercontent.com/assets/13706907/13090523/a5db1412-d4f6-11e5-95c9-9263ca613479.PNG)

**Comment by sgtcaze** [comment]
Cool, thank you. When you do not have NametagEdit on your server - this error doesn't appear?

Edit: the issue might be us shading a different version of HikariCP, and LogBlock using a different version. 

See here: https://github.com/LogBlock/LogBlock/blob/master/pom.xml#L70
https://github.com/sgtcaze/NametagEdit/blob/master/pom.xml#L63

We might update to Java7 for HikariCP.

**Comment by Greenman1805** [comment]
Yes, when NametagEdit isn't on the server, the error doesn't appear.

I'm on Java8, maybe this could also be a problem?

**Comment by sgtcaze** [comment]
Please try #23 and see if this fixes anything
http://ci.playmc.cc/job/NametagEdit/23/

**Comment by Greenman1805** [comment]
Build #23 works for me, no errors in the server logs and both plugins Logblock and NametagEdit are working correctly. Thank you!
