### ISSUE TITLE
Team Scoreboard Error

### ISSUE THREAD

**Issue by morpig** [sgtcaze/NametagEdit#23]
Hey @sgtcaze,

Having this weird problem. Running on BungeeCord, custom spigot build (1.8) and this happens.

```java
java.lang.IllegalArgumentException: Team NTE2 already exists in this scoreboard
        at com.google.common.base.Preconditions.checkArgument(Preconditions.java:145)
        at net.md_5.bungee.api.score.Scoreboard.addTeam(Scoreboard.java:68)
        at net.md_5.bungee.connection.DownstreamBridge.handle(DownstreamBridge.java:182)
        at net.md_5.bungee.protocol.packet.Team.handle(Team.java:106)
        at net.md_5.bungee.netty.HandlerBoss.channelRead(HandlerBoss.java:75)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:333)
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:319)
        at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:163)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:333)
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:319)
        at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:163)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:333)
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:319)
        at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:163)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:333)
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:319)
        at io.netty.handler.timeout.ReadTimeoutHandler.channelRead(ReadTimeoutHandler.java:150)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:333)
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:319)
        at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:787)
        at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:130)
        at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:511)
        at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:468)
        at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:382)
        at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:354)
        at java.lang.Thread.run(Thread.java:745)

```

Any ideas? I have you on skype, but just want to put it here. ;-)

**Comment by sgtcaze** [comment]
This is bizarre. Have you reloaded?

Also
*Plugin version?
*Server version?

**Comment by morpig** [comment]
I'm running on sgtcaze/NametagEdit@56c7265a4d59bdc528994ca2f79199330e3374b1. Server version: 1.8-R0.1-SNAPSHOT (spigot)

**Comment by sgtcaze** [comment]
Any plugins that alter the scoreboard? Do you use the API?

**Comment by morpig** [comment]
I only use NTE for scoreboard and nametag things, and yes I use NTE API. 

Maybe I'm wrong (but correct me):
https://gist.github.com/morpig/fafbeb6901f3687b1665

**Comment by sgtcaze** [comment]
I will add a function to clear the existing tag. 

See this

https://github.com/sgtcaze/NametagEdit/blob/master/src/main/java/ca/wacos/nametagedit/events/PlayerJoin.java#L23

We clear the tag before we apply a new one

**Comment by morpig** [comment]
Hmm, ok.

I was also finding the resetNametag (if i'm not mistaken), but on the new version can't find it.

Btw thanks!

**Comment by sgtcaze** [comment]
The API now has a new method to address this. You can find it here:

https://github.com/sgtcaze/NametagEdit/commit/043d9af8f445208f11916d691d1f8b15687c1cd3
