### ISSUE TITLE
A team with the name '' already exists!

### ISSUE THREAD

**Issue by 011248163264** [sgtcaze/NametagEdit#318]
# Bug Report

**Type /ver NametagEdit and post the output.**
4.2.0

**What version of Bukkit/Spigot/PaperSpigot are you using? Type /ver**
spigot 1.13
nte with mysql support
client 1.13.2

**What plugins are you using? Type /plugins**
pex, plotsquared,worldedit, worldguard, viaversion, vault,pac,protocollib, essentials

**Please explain your issue. How do you trigger it?**
hm the nte is not working, on all other 1.12.2 servers is this ok but not on 1.13

**Are there any errors in the console? Please use: https://pastebin.com**

 [00:54:07] [Client thread/FATAL]: Error executing task
[B#397]  java.util.concurrent.ExecutionException: java.lang.IllegalArgumentException: A team with the name '' already exists!
[B#397]  	at java.util.concurrent.FutureTask.report(FutureTask.java:122) ~[?:1.8.0_191]
[B#397]  	at java.util.concurrent.FutureTask.get(FutureTask.java:192) ~[?:1.8.0_191]
[B#397]  	at k.a(SourceFile:199) [minecraft.jar:?]
[B#397]  	at cfi.c(SourceFile:808) [minecraft.jar:?]
[B#397]  	at cfi.a(SourceFile:392) [minecraft.jar:?]
[B#397]  	at net.minecraft.client.main.Main.main(SourceFile:144) [minecraft.jar:?]
[B#397]  Caused by: java.lang.IllegalArgumentException: A team with the name '' already exists!
[B#397]  	at cer.g(SourceFile:188) ~[minecraft.jar:?]
[B#397]  	at cqs.a(SourceFile:1767) ~[minecraft.jar:?]
[B#397]  	at lo.a(SourceFile:122) ~[minecraft.jar:?]
[B#397]  	at lo.a(SourceFile:16) ~[minecraft.jar:?]
[B#397]  	at ix.a(SourceFile:10) ~[minecraft.jar:?]
[B#397]  	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) ~[?:1.8.0_191]
[B#397]  	at java.util.concurrent.FutureTask.run(FutureTask.java:266) ~[?:1.8.0_191]
[B#397]  	at k.a(SourceFile:198) ~[minecraft.jar:?]
[B#397]  	... 3 more

[00:49:54] [Craft Scheduler Thread - 1/INFO]: [NametagEdit] [DEBUG] Applying GroupTag to Eeassy
[00:49:54] [Server thread/INFO]: [NametagEdit] [DEBUG] Created FakeTeam FFPFD_AA3. Size: 1
[00:49:54] [Server thread/INFO]: [NametagEdit] [DEBUG] Eeassy has been added to team FFPFD_AA3
[00:51:25] [Craft Scheduler Thread - 12/INFO]: [MysqlInventoryBridge] Saving online players data...
[00:51:25] [Craft Scheduler Thread - 12/INFO]: [MysqlInventoryBridge] Data save complete for 1 players.
[00:53:40] [User Authenticator #4/INFO]: UUID of player DosePlay is 4f4fd805-f2bd-3bdc-abd6-22b1dcddde53
[00:53:41] [Server thread/INFO]: DosePlay[localhost.localdomain/127.0.0.1:46916] logged in with entity id 41585 at ([cb1]-151.31248624776956, 66.0, 222.2526678405442)
[00:53:41] [Craft Scheduler Thread - 4/INFO]: [NametagEdit] [DEBUG] Applying GroupTag to DosePlay
[00:53:41] [Server thread/INFO]: [NametagEdit] [DEBUG] Created FakeTeam FFPFD_A4. Size: 2
[00:53:41] [Server thread/INFO]: [NametagEdit] [DEBUG] DosePlay has been added to team FFPFD_A4
[00:53:52] [Server thread/INFO]: DosePlay issued server command: /nte reload
[00:53:52] [Server thread/INFO]: [NametagEdit] [DEBUG] Applied tags to all online players.
[00:53:52] [Craft Scheduler Thread - 14/INFO]: [NametagEdit] [DEBUG] Applying GroupTag to Eeassy
[00:53:52] [Craft Scheduler Thread - 12/INFO]: [NametagEdit] [DEBUG] Applying GroupTag to DosePlay
[00:53:52] [Server thread/INFO]: [NametagEdit] [DEBUG] Created FakeTeam FFPFD_AA5. Size: 1
[00:53:52] [Server thread/INFO]: [NametagEdit] [DEBUG] Eeassy has been added to team FFPFD_AA5
[00:53:52] [Server thread/INFO]: [NametagEdit] [DEBUG] Created FakeTeam FFPFD_A6. Size: 2
[00:53:52] [Server thread/INFO]: [NametagEdit] [DEBUG] DosePlay has been added to team FFPFD_A6

**Comment by 011248163264** [comment]
Hi i have also try to change from the mysql to file support, and its the same issue.
Hope you can help.

**Comment by 011248163264** [comment]
are there support here ? No ide ?

**Comment by jsuarezl** [comment]
Seems that the problem is from another plugin, try removing PAC

**Comment by 011248163264** [comment]
Hi hm ok i try this

**Comment by 011248163264** [comment]
Hi hm ok i try this

**Comment by 011248163264** [comment]
hm is the same issue

**Comment by 011248163264** [comment]
i have also try to install a clean 1.13 server with nte but is not working , there are no name tags and the same issue

**Comment by 011248163264** [comment]
its the same also on 1.13.1 and 1.13.2, with the latest spigotbuild

**Comment by jsuarezl** [comment]
try deleting the scoreboard.dat file inside the main world folder

**Comment by Malachiel87** [comment]
Same issue for me but is estremly rare, using waterfall and paperspigot 1.12.2 (latest release)
bungee: https://gist.github.com/xion87/e980fc667f4cd3c5480b73fe4920e046
paperspigot (with debug enabled) https://gist.github.com/xion87/08409681d3f197bc65838296ee819221

and sometimes all tags will gone and work again after reload NTE again,

**Comment by JustOneMoreBlock** [comment]
Unfortunately, this error doesn't seem to connect to NametagEdit at all. While we do use scoreboards. I'm not seeing any errors that are indicating the issue is being on your end.
