### ISSUE TITLE
nametagedit conflicting with luckperms.

### ISSUE THREAD

**Issue by BugadoGC** [sgtcaze/NametagEdit#415]
# Bug Report

**Type /ver NametagEdit and post the output.**
NametagEdit version 4.4.6

**What version of Bukkit/Spigot/PaperSpigot are you using? Type /ver**

**What plugins are you using? Type /plugins**
git-Spigot-db6de12-18fbb24 (MC: 1.8.8) (Implementing API version 1.8.8-R-0.1-SNAPSHOT)

**Please explain your issue. How do you trigger it?**
Basically nametagedit is conflicting with luckperms

**Are there any errors in the console? Please use: https://pastebin.com**
https://pastebin.com/MqQvNWrh

**Comment by SladeHazard** [comment]
agree happening with everyone my server version 1.12.2 plugin not loadng
[19:30:33] [Server thread/INFO]: [NametagEdit] Enabling NametagEdit v4.4.6
[19:30:33] [Server thread/INFO]: [NametagEdit] Found LuckPerms! Hooking in.
[19:30:33] [Server thread/ERROR]: Error occurred while enabling NametagEdit v4.4.6 (Is it up to date?)
java.lang.NoClassDefFoundError: net/luckperms/api/LuckPermsProvider
	at com.nametagedit.plugin.hooks.HookLuckPerms.<init>(HookLuckPerms.java:19) ~[?:?]
	at com.nametagedit.plugin.NametagEdit.onEnable(NametagEdit.java:54) ~[?:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264) ~[patched_1.12.2.jar:git-Paper-1618]
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:316) ~[patched_1.12.2.jar:git-Paper-1618]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:405) ~[patched_1.12.2.jar:git-Paper-1618]
	at org.bukkit.craftbukkit.v1_12_R1.CraftServer.enablePlugin(CraftServer.java:395) ~[patched_1.12.2.jar:git-Paper-1618]
	at org.bukkit.craftbukkit.v1_12_R1.CraftServer.enablePlugins(CraftServer.java:344) ~[patched_1.12.2.jar:git-Paper-1618]
	at net.minecraft.server.v1_12_R1.MinecraftServer.t(MinecraftServer.java:442) ~[patched_1.12.2.jar:git-Paper-1618]
	at net.minecraft.server.v1_12_R1.MinecraftServer.l(MinecraftServer.java:403) ~[patched_1.12.2.jar:git-Paper-1618]
	at net.minecraft.server.v1_12_R1.MinecraftServer.a(MinecraftServer.java:341) ~[patched_1.12.2.jar:git-Paper-1618]
	at net.minecraft.server.v1_12_R1.DedicatedServer.init(DedicatedServer.java:289) ~[patched_1.12.2.jar:git-Paper-1618]
	at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:616) ~[patched_1.12.2.jar:git-Paper-1618]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_221]
Caused by: java.lang.ClassNotFoundException: net.luckperms.api.LuckPermsProvider
	at java.net.URLClassLoader.findClass(URLClassLoader.java:382) ~[?:1.8.0_221]
	at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:156) ~[patched_1.12.2.jar:git-Paper-1618]
	at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:104) ~[patched_1.12.2.jar:git-Paper-1618]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424) ~[?:1.8.0_221]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357) ~[?:1.8.0_221]
	... 13 more
[19:30:33] [Server thread/INFO]: [NametagEdit] Disabling NametagEdit v4.4.6

**Comment by x9nico** [comment]
It's because you don't have the dev version of LuckPerms.
You can download the version there: https://ci.lucko.me/job/LuckPerms/lastSuccessfulBuild/artifact/bukkit/build/libs/LuckPerms-Bukkit-5.0.23.jar

**Comment by Nooxico** [comment]
I've de same problem but your link does not work....

**Comment by x9nico** [comment]
https://ci.lucko.me/job/LuckPerms/lastSuccessfulBuild/artifact/bukkit/build/libs/LuckPerms-Bukkit-5.0.56.jar
Try this link now, it's because they released a new build. @NoxTV
