### ISSUE TITLE
Group Order Not Working

### ISSUE THREAD

**Issue by ghost** [sgtcaze/NametagEdit#420]
# Bug Report

**Type /ver NametagEdit and post the output.**

I don't know what that is!!

**What version of Bukkit/Spigot/PaperSpigot are you using? Type /ver**

[13:10:14 INFO]: This server is running CraftBukkit version git-Spigot-db6de12-18fbb24 (MC: 1.8.8) (Implementing API version 1.8.8-R0.1-SNAPSHOT)

**What plugins are you using? Type /plugins**

BlockParticles, BarAPI, NametagEdit, SkinsRestorer, DeluxeTags, NoteBlockAPI, icJukeBox, LuckPerms, AnimationLib, PacketListenerApi, AutoBroadcast, WorldBorder, Horizon, Interactables, BannerBoard, AntiWDL, MovingDevApi, MVdWPlaceholderAPI, FastAsyncWorldEdit, FeatherBoard, ConditionalCommands, Vault, BossBar, RankGrantPlus, LuckPermsGUI, RewardPRO, ViaVersion, StaffPlus, WorldEdit, PortalCommands, Essentials, DecoHeads, ProtocolLib, LibsDisguises, Citizens, EssentialsChat, CasualProtector, DeluxeHub, UltraCosmetics, HolographicDisplays, WorldGuard, CommandNPC, EssentialsSpawn, EssentialsMysqlStorage, CompatNoCheatPlus, BlockCommandTab, NoCheatPlus, ItemJoin, NCPDragDown

**Please explain your issue. How do you trigger it?**

its not letting me create a group order

**Are there any errors in the console? Please use: https://pastebin.com**

[13:05:51 INFO]: RealAshuGamer issued server command: /nte group order owner admin developer
[13:05:51 WARN]: java.sql.SQLException: Column count doesn't match value count at row 1
[13:05:51 WARN]:        at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:1073)
[13:05:51 WARN]:        at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3593)
[13:05:51 WARN]:        at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3525)
[13:05:51 WARN]:        at com.mysql.jdbc.MysqlIO.sendCommand(MysqlIO.java:1986)
[13:05:51 WARN]:        at com.mysql.jdbc.MysqlIO.sqlQueryDirect(MysqlIO.java:2140)
[13:05:51 WARN]:        at com.mysql.jdbc.ConnectionImpl.execSQL(ConnectionImpl.java:2626)
[13:05:51 WARN]:        at com.mysql.jdbc.PreparedStatement.executeInternal(PreparedStatement.java:2111)
[13:05:51 WARN]:        at com.mysql.jdbc.PreparedStatement.execute(PreparedStatement.java:1362)
[13:05:51 WARN]:        at com.zaxxer.hikari.pool.ProxyPreparedStatement.execute(ProxyPreparedStatement.java:44)
[13:05:51 WARN]:        at com.zaxxer.hikari.pool.HikariProxyPreparedStatement.execute(HikariProxyPreparedStatement.java)
[13:05:51 WARN]:        at com.nametagedit.plugin.storage.database.tasks.GroupConfigUpdater.run(GroupConfigUpdater.java:27)
[13:05:51 WARN]:        at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftTask.run(CraftTask.java:71)
[13:05:51 WARN]:        at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:53)
[13:05:51 WARN]:        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
[13:05:51 WARN]:        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
[13:05:51 WARN]:        at java.lang.Thread.run(Thread.java:748)

**Comment by Probag586** [comment]
i have the same problem, you have solved?
