### ISSUE TITLE
Problem with luckperms

### ISSUE THREAD

**Issue by Alee-OneHit** [sgtcaze/NametagEdit#448]
hi, it's been 1 month since I have a problem with another plugin, which is nametagedit, it throws me an error that I can't fix by updating the same plugin, since the updates higher than 4.4.1, they close the server, and check that it is not the plugin nametagedit, even so when I use 4.4.1 of luckperms I get an error with the other plugin and that does not let me use the commands within the game, create the error problem that both plugins have.

[19:04:23 INFO]: [NametagEdit] Found LuckPerms! Hooking in.
[19:04:23 ERROR]: Error occurred while enabling NametagEdit v4.4.6 (Is it up to date?)
java.lang.NoClassDefFoundError: net/luckperms/api/LuckPermsProvider
at com.nametagedit.plugin.hooks.HookLuckPerms.(HookLuckPerms.java:19) ~[?:?]
at com.nametagedit.plugin.NametagEdit.onEnable(NametagEdit.java:54) ~[?:?]
at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:177) ~[JavaPlugin.class:9d300c6]
at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:327) [JavaPluginLoader.class:9d300c6]
at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:399) [SimplePluginManager.class:9d300c6]
at org.bukkit.craftbukkit.v1_12_R1.CraftServer.enablePlugin(CraftServer.java:489) [CraftServer.class:9d300c6]
at org.bukkit.craftbukkit.v1_12_R1.CraftServer.enablePlugins(CraftServer.java:418) [CraftServer.class:9d300c6]
at net.minecraft.server.MinecraftServer.func_71247_a(MinecraftServer.java:384) [MinecraftServer.class:?]
at net.minecraft.server.dedicated.DedicatedServer.func_71197_b(DedicatedServer.java:319) [nz.class:?]
at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:588) [MinecraftServer.class:?]
at java.lang.Thread.run(Unknown Source) [?:1.8.0_241]
Caused by: java.lang.ClassNotFoundException: net.luckperms.api.LuckPermsProvider
at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:106) ~[PluginClassLoader.class:9d300c6]
at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:75) ~[PluginClassLoader.class:9d300c6]
at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_241]
at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_241]
... 11 more

**Comment by DarkNova101** [comment]
#161

**Comment by alfiejfs** [comment]
It looks like you are using the wrong version of either plugin. Make sure you are using the 1.12 releases of both NTE and LuckPerms (though I am unsure NTE supported LuckPerms in 1.12, as noted in the PR linked above). 

My only suggestions would be to either use a different permissions plugin or update to the latest version

**Comment by JustOneMoreBlock** [comment]
- NTE works regardless of which version.
- With that said, needs to update to the latest LuckPerms.
