### ISSUE TITLE
Group problem

### ISSUE THREAD

**Issue by jeannen** [sgtcaze/NametagEdit#45]
Hi :)
Here is my groups.yml

Groups:
  Vagabond: # This is the 'key' or the thing to distinguish this group
     Permission: Grade.Vagabond # This is the permission required to have this nametag - it can be anything
     Prefix: '&7[V]' # Both Prefix/Suffix are REQUIRED, even if they are blank. String length will be automatically appended
     Suffix: ''

But in game, nothing happend, i must use the manuel way (command) player by player, groups otpion don't works (no error in log)

Plugin version: 3.0
Spigot version: 1.8.3

**Comment by sgtcaze** [comment]
Please tryout http://ci.playmc.cc/job/NametagEdit/13/ and let me know if anything changes

**Comment by jeannen** [comment]
It work, but there is a problem with ineritance (I don't know how we spell it sorry :P ), so, a player with the first grade and the last grade are both going to have the first grade above their head

And, in can't /ne clear a title, and event if i delete the file, the title come back again, please fix this :/

**Comment by sgtcaze** [comment]
Are you still experiencing this issue? If so, please share your permissions (zperms/group manager/bperms etc) and groups.yml file (nametagedits)

**Comment by jeannen** [comment]
Yep, and with the new dev build i've got this: [12:48:07 WARN]: [NametagEdit] Task #60 for NametagEdit v3.0.1 generated an exception
java.lang.NullPointerException
at ca.wacos.nametagedit.Messages.send(Messages.java:45) ~[?:?]
at ca.wacos.nametagedit.core.NametagHandler.reload(NametagHandler.java:99) ~[?:?]
at ca.wacos.nametagedit.core.NametagHandler$1.run(NametagHandler.java:64) ~[?:?]
at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftTask.run(CraftTask.java:71) ~[spigot_vgbin.jar:git-Spigot-d2856ae-8f0f4ed]
at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:350) [spigot_vgbin.jar:git-Spigot-d2856ae-8f0f4ed]
at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:726) [spigot_vgbin.jar:git-Spigot-d2856ae-8f0f4ed]
at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:367) [spigot_vgbin.jar:git-Spigot-d2856ae-8f0f4ed]
at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:657) [spigot_vgbin.jar:git-Spigot-d2856ae-8f0f4ed]
at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:560) [spigot_vgbin.jar:git-Spigot-d2856ae-8f0f4ed]
at java.lang.Thread.run(Thread.java:745) [?:1.7.0_75]

**Comment by sgtcaze** [comment]
Line 99 cannot through a null pointer since it checks if the variable is null. This indicates you are running an older build. Please use:

http://ci.playmc.cc/job/NametagEdit/16/

And let me know how it goes.

**Comment by sgtcaze** [comment]
Closing this for now as this line cannot throw a NPE with builds 16+.
