### ISSUE TITLE
Unable to use "/nte group order xxx xxx"

### ISSUE THREAD

**Issue by im-zhou** [sgtcaze/NametagEdit#467]
# Bug Report

[16:44:17 INFO]: NametagEdit version 4.4.8
[16:44:17 INFO]: Authors: sgtcaze and Cory

**What version of Bukkit/Spigot/PaperSpigot are you using? Type /ver**

[16:44:09 INFO]: This server is running Paper version git-Paper-240 (MC: 1.15.2) (Implementing API version 1.15.2-R0.1-SNAPSHOT)
[16:44:09 INFO]: Checking version, please wait...
[16:44:10 INFO]: Previous version: git-Paper-126 (MC: 1.15.2)
[16:44:10 INFO]: You are 8 version(s) behind

**What plugins are you using? Type /plugins**

[16:45:22 INFO]: Plugins (23): bungeelaba*, CashCode*, DailyReward, DeluxeChat, DeluxeJoin, DeluxeMenus, FlyCommand*, GadgetsMenu, HolographicDisplays, LuckPerms, NametagEdit*, Nicky*, PlaceholderAPI, PlayerPoints*, PlugMan, ProtocolLib, RainbowChat*, SQLibrary*, SuperLobby, TitleManager, Vault, ViaBackwards, ViaVersion

**Please explain your issue. How do you trigger it?**

When i use "/nte group order admin svip vip default"

**Are there any errors in the console? Please use: https://pastebin.com**
Sorry, I don't know how to use it

[16:32:50 INFO]: sky_xc issued server command: /nte group order admin svip vip default
[16:32:51 WARN]: java.sql.SQLException: Column count doesn't match value count at row 1
[16:32:51 WARN]:        at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:965)
[16:32:51 WARN]:        at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3933)
[16:32:51 WARN]:        at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3869)
[16:32:51 WARN]:        at com.mysql.jdbc.MysqlIO.sendCommand(MysqlIO.java:2524)
[16:32:51 WARN]:        at com.mysql.jdbc.MysqlIO.sqlQueryDirect(MysqlIO.java:2675)
[16:32:51 WARN]:        at com.mysql.jdbc.ConnectionImpl.execSQL(ConnectionImpl.java:2465)
[16:32:51 WARN]:        at com.mysql.jdbc.PreparedStatement.executeInternal(PreparedStatement.java:1912)
[16:32:51 WARN]:        at com.mysql.jdbc.PreparedStatement.execute(PreparedStatement.java:1251)
[16:32:51 WARN]:        at com.zaxxer.hikari.pool.ProxyPreparedStatement.execute(ProxyPreparedStatement.java:44)
[16:32:51 WARN]:        at com.zaxxer.hikari.pool.HikariProxyPreparedStatement.execute(HikariProxyPreparedStatement.java)
[16:32:51 WARN]:        at com.nametagedit.plugin.storage.database.tasks.GroupConfigUpdater.run(GroupConfigUpdater.java:27)
[16:32:51 WARN]:        at org.bukkit.craftbukkit.v1_15_R1.scheduler.CraftTask.run(CraftTask.java:84)
[16:32:51 WARN]:        at org.bukkit.craftbukkit.v1_15_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:54)
[16:32:51 WARN]:        at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22)
[16:32:51 WARN]:        at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
[16:32:51 WARN]:        at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
[16:32:51 WARN]:        at java.lang.Thread.run(Unknown Source)

**Comment by Lightcaster5** [comment]
From what I can tell, it looks like your SQL database settings in the config or wrong, OR, you used /reload or /plugman reload NametagEdit and it didn't update the players already connected because no PlayerJoinEvent was triggered. Take a look at your configuration file, in the SQL settings, and stop using /reload or /plugman reload <plugin-name>! You should only use plugman if you are a plugin developer and are making changes to your code a lot!!!
