### ISSUE TITLE
Consol error on logout

### ISSUE THREAD

**Issue by titidelaff** [sgtcaze/NametagEdit#489]
> 
[15:23:04 WARN]: [NametagEdit] Task #41352 for NametagEdit v4.4.8 generated an exception
java.lang.NullPointerException: null
        at net.Indyuce.mmocore.api.player.PlayerData.get(PlayerData.java:146) ~[?:?]
        at net.Indyuce.mmocore.comp.placeholder.RPGPlaceholders.onPlaceholderRequest(RPGPlaceholders.java:40) ~[?:?]
        at me.clip.placeholderapi.PlaceholderHook.onRequest(PlaceholderHook.java:41) ~[?:?]
        at me.clip.placeholderapi.PlaceholderAPI.setPlaceholders(PlaceholderAPI.java:326) ~[?:?]
        at me.clip.placeholderapi.PlaceholderAPI.setPlaceholders(PlaceholderAPI.java:525) ~[?:?]
        at com.nametagedit.plugin.NametagHandler.formatWithPlaceholders(NametagHandler.java:309) ~[?:?]
        at com.nametagedit.plugin.NametagHandler$8.run(NametagHandler.java:408) ~[?:?]
        at org.bukkit.craftbukkit.v1_15_R1.scheduler.CraftTask.run(CraftTask.java:84) ~[patched_1.15.2.jar:git-Paper-312]
        at org.bukkit.craftbukkit.v1_15_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:461) ~[patched_1.15.2.jar:git-Paper-312]
        at net.minecraft.server.v1_15_R1.MinecraftServer.b(MinecraftServer.java:1256) ~[patched_1.15.2.jar:git-Paper-312]
        at net.minecraft.server.v1_15_R1.DedicatedServer.b(DedicatedServer.java:430) ~[patched_1.15.2.jar:git-Paper-312]
        at net.minecraft.server.v1_15_R1.MinecraftServer.a(MinecraftServer.java:1173) ~[patched_1.15.2.jar:git-Paper-312]
        at net.minecraft.server.v1_15_R1.MinecraftServer.run(MinecraftServer.java:962) ~[patched_1.15.2.jar:git-Paper-312]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_252]

**Comment by Ithirul** [comment]
This is still a problem even after v4.4.10. While it doesn't seem to work incorrectly, it spams the console quite a bit.
