### ISSUE TITLE
Dev2 Testing

### ISSUE THREAD

**Issue by JustOneMoreBlock** [sgtcaze/NametagEdit#620]
HEX COLORS WORK!

```
/nte player NametagEdit prefix '&#F50B16&lR&#0FF50B&lG&#0B52F5&lB &r'
```

```
/nte player NametagEdit suffix ' &#F50B16&lR&#0FF50B&lG&#0B52F5&lB'
```
https://i.imgur.com/VpEMqpy.png

At the end for `&r` you can change this for your name color.

```
/nte player NametagEdit suffix '&#F50B16&lR&#0FF50B&lG&#0B52F5&lB &c'
```
https://i.imgur.com/Tsl9wTq.png

https://github.com/sgtcaze/NametagEdit/issues/588

- If you add an `&c&l` for `BOLD`. It removes the color and makes it white and then it's bold.
- Tried making it a hex color `&#0FF50B&l`
- Works fine in 1.8.x https://i.imgur.com/BurLtcY.png

This error presented itself when creating new tables regardless of version.

```
04.07 12:12:10 [Server] INFO NametagEdit Pool - Start completed.
04.07 12:12:10 [Server] ERROR NametagEdit Query Failed - Reason: Table 'apexMC103008.nte_config' doesn't exist
04.07 12:12:10 [Server] ERROR If this is not a connection error, please enable debug with /nte debug and post the error on our GitHub Issue Tracker.
04.07 12:12:10 [Server] ERROR NametagEdit Query Failed - Reason: Duplicate column name 'priority'
04.07 12:12:10 [Server] ERROR If this is not a connection error, please enable debug with /nte debug and post the error on our GitHub Issue Tracker.
04.07 12:12:10 [Server] ERROR NametagEdit Query Failed - Reason: Duplicate column name 'priority'
04.07 12:12:10 [Server] ERROR If this is not a connection error, please enable debug with /nte debug and post the error on our GitHub Issue Tracker.
```
- Error goes away after restart.
- `INFO NametagEdit Pool - Driver does not support get/set network timeout for connections. (com.mysql.jdbc.JDBC4Connection.getNetworkTimeout()I)` This error doesn't appear to be present on 1.17.

https://github.com/sgtcaze/NametagEdit/issues/609

Note: Probably need to increase the limit from 128 to 256. (Max on Chat)
Perhaps could look into an web editor like LuckPerms for easier management.

```
04.07 14:06:48 [Server] WARN java.sql.BatchUpdateException: Data truncation: Data too long for column 'prefix' at row 1
04.07 14:06:48 [Server] WARN at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
04.07 14:06:48 [Server] WARN at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
04.07 14:06:48 [Server] WARN at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
04.07 14:06:48 [Server] WARN at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:490)
04.07 14:06:48 [Server] WARN at com.mysql.cj.util.Util.handleNewInstance(Util.java:192)
04.07 14:06:48 [Server] WARN at com.mysql.cj.util.Util.getInstance(Util.java:167)
04.07 14:06:48 [Server] WARN at com.mysql.cj.util.Util.getInstance(Util.java:174)
04.07 14:06:48 [Server] WARN at com.mysql.cj.jdbc.exceptions.SQLError.createBatchUpdateException(SQLError.java:224)
04.07 14:06:48 [Server] WARN at com.mysql.cj.jdbc.ClientPreparedStatement.executeBatchSerially(ClientPreparedStatement.java:853)
04.07 14:06:48 [Server] WARN at com.mysql.cj.jdbc.ClientPreparedStatement.executeBatchInternal(ClientPreparedStatement.java:435)
04.07 14:06:48 [Server] WARN at com.mysql.cj.jdbc.StatementImpl.executeBatch(StatementImpl.java:794)
04.07 14:06:48 [Server] WARN at com.zaxxer.hikari.pool.ProxyStatement.executeBatch(ProxyStatement.java:127)
04.07 14:06:48 [Server] WARN at com.zaxxer.hikari.pool.HikariProxyPreparedStatement.executeBatch(HikariProxyPreparedStatement.java)
04.07 14:06:48 [Server] WARN at com.nametagedit.plugin.storage.database.tasks.PlayerSaver.run(PlayerSaver.java:38)
04.07 14:06:48 [Server] WARN at org.bukkit.craftbukkit.v1_16_R3.scheduler.CraftTask.run(CraftTask.java:100)
04.07 14:06:48 [Server] WARN at org.bukkit.craftbukkit.v1_16_R3.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:54)
04.07 14:06:48 [Server] WARN at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22)
04.07 14:06:48 [Server] WARN at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
04.07 14:06:48 [Server] WARN at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
04.07 14:06:48 [Server] WARN at java.base/java.lang.Thread.run(Thread.java:829)
04.07 14:06:48 [Server] WARN Caused by: com.mysql.cj.jdbc.exceptions.MysqlDataTruncation: Data truncation: Data too long for column 'prefix' at row 1
04.07 14:06:48 [Server] WARN at com.mysql.cj.jdbc.exceptions.SQLExceptionsMapping.translateException(SQLExceptionsMapping.java:104)
04.07 14:06:48 [Server] WARN at com.mysql.cj.jdbc.ClientPreparedStatement.executeInternal(ClientPreparedStatement.java:953)
04.07 14:06:48 [Server] WARN at com.mysql.cj.jdbc.ClientPreparedStatement.executeUpdateInternal(ClientPreparedStatement.java:1092)
04.07 14:06:48 [Server] WARN at com.mysql.cj.jdbc.ClientPreparedStatement.executeBatchSerially(ClientPreparedStatement.java:832)
04.07 14:06:48 [Server] WARN ... 11 more
```

Also, look into https://github.com/sgtcaze/NametagEdit/issues/616 If you don't mind.

@Lorenzo0111 and/or @Aurelien30000

**Comment by Lorenzo0111** [comment]
I’m actually developing a web editor for my plugin, maybe I can adapt it for NametagEdit.

**Edit:** #622, the plugin part is ready. Can someone help me writing the web part?

**Comment by JustOneMoreBlock** [comment]
> I’m actually developing a web editor for my plugin, maybe I can adapt it for NametagEdit.
> 
> **Edit:** #622, the plugin part is ready. Can someone help me writing the web part?

What do you need exactly for the web part? :P

**Comment by Lorenzo0111** [comment]
> 
> 
> > I’m actually developing a web editor for my plugin, maybe I can adapt it for NametagEdit.
> > **Edit:** #622, the plugin part is ready. Can someone help me writing the web part?
> 
> What do you need exactly for the web part? :P

everything :p

**Comment by JustOneMoreBlock** [comment]
Would it work similar to https://luckperms.net/editor/demo and then they type and update command in-game?

https://github.com/lucko/LuckPermsWeb

It's under MIT. So, we can legally use it. If needed. :)

Realistically, most of everything is there. Just need to change a few things around in the context of NTE and your plugin.

**Comment by Lorenzo0111** [comment]
Do you have any preference about the graphic part?

**Comment by JustOneMoreBlock** [comment]
> Do you have any preference about the graphic part?

What do you mean? :P
