### ISSUE TITLE
In-game Commands Not Working.

### ISSUE THREAD

**Issue by ItsSchatten** [sgtcaze/NametagEdit#66]
I get this error in 1.10.2 Spigot,

[14:35:41 INFO]: ItsShadow13 issued server command: /ne
[14:35:41 WARN]: Argument could not be passed.
java.lang.NumberFormatException: For input string: "R"
        at java.lang.NumberFormatException.forInputString(Unknown Source) ~[?:1.8.0_92]
        at java.lang.Integer.parseInt(Unknown Source) ~[?:1.8.0_92]
        at java.lang.Integer.parseInt(Unknown Source) ~[?:1.8.0_92]
        at mkremins.fanciful.FancyMessage.createChatPacket(FancyMessage.java:644) ~[NametagEdit%20(1).jar:?]
        at mkremins.fanciful.FancyMessage.send(FancyMessage.java:617) [NametagEdit%20(1).jar:?]
        at mkremins.fanciful.FancyMessage.send(FancyMessage.java:682) [NametagEdit%20(1).jar:?]
        at com.nametagedit.plugin.NametagCommand.sendUsage(NametagCommand.java:62) [NametagEdit%20(1).jar:?]
        at com.nametagedit.plugin.NametagCommand.onCommand(NametagCommand.java:34) [NametagEdit%20(1).jar:?]
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44) [spigot.jar:git-Spigot-a9631d2-56813c7]
        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:141) [spigot.jar:git-Spigot-a9631d2-56813c7]
        at org.bukkit.craftbukkit.v1_10_R1.CraftServer.dispatchCommand(CraftServer.java:646) [spigot.jar:git-Spigot-a9631d2-56813c7]
        at net.minecraft.server.v1_10_R1.PlayerConnection.handleCommand(PlayerConnection.java:1351) [spigot.jar:git-Spigot-a9631d2-56813c7]
        at net.minecraft.server.v1_10_R1.PlayerConnection.a(PlayerConnection.java:1186) [spigot.jar:git-Spigot-a9631d2-56813c7]
        at net.minecraft.server.v1_10_R1.PacketPlayInChat.a(PacketPlayInChat.java:45) [spigot.jar:git-Spigot-a9631d2-56813c7]
        at net.minecraft.server.v1_10_R1.PacketPlayInChat.a(PacketPlayInChat.java:1) [spigot.jar:git-Spigot-a9631d2-56813c7]
        at net.minecraft.server.v1_10_R1.PlayerConnectionUtils$1.run(SourceFile:13) [spigot.jar:git-Spigot-a9631d2-56813c7]
        at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) [?:1.8.0_92]
        at java.util.concurrent.FutureTask.run(Unknown Source) [?:1.8.0_92]
        at net.minecraft.server.v1_10_R1.SystemUtils.a(SourceFile:45) [spigot.jar:git-Spigot-a9631d2-56813c7]
        at net.minecraft.server.v1_10_R1.MinecraftServer.D(MinecraftServer.java:737) [spigot.jar:git-Spigot-a9631d2-56813c7]
        at net.minecraft.server.v1_10_R1.DedicatedServer.D(DedicatedServer.java:399) [spigot.jar:git-Spigot-a9631d2-56813c7]
        at net.minecraft.server.v1_10_R1.MinecraftServer.C(MinecraftServer.java:673) [spigot.jar:git-Spigot-a9631d2-56813c7]
        at net.minecraft.server.v1_10_R1.MinecraftServer.run(MinecraftServer.java:572) [spigot.jar:git-Spigot-a9631d2-56813c7]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_92]

**Comment by ItsSchatten** [comment]
I should also mention, commands via the console work perfectly fine.

**Comment by JustOneMoreBlock** [comment]
What build are you using?

**Comment by sgtcaze** [comment]
Try out #34 http://ci.playmc.cc/job/NametagEdit/34/
This will fix your issue.
