### ISSUE TITLE
1.18

### ISSUE THREAD

**Issue by JustOneMoreBlock** [sgtcaze/NametagEdit#673]
# Bug Report

**Type /ver NametagEdit and post the output.**
4.5.2 (Staging)

**What version of Bukkit/Spigot/PaperSpigot are you using? Type /ver**
1.18

**What plugins are you using? Type /plugins**
Just NTE

**Please explain your issue. How do you trigger it?**
Doesn't load.

**Are there any errors in the console? Please use: https://pastebin.com**

```
30.11 22:13:15 [Server] INFO [NametagEdit] Enabling NametagEdit v4.5.2
30.11 22:13:15 [Server] WARN java.lang.NoSuchMethodException: net.minecraft.server.network.PlayerConnection.sendPacket(net.minecraft.network.protocol.Packet)
30.11 22:13:15 [Server] WARN at java.base/java.lang.Class.getMethod(Class.java:2227)
30.11 22:13:15 [Server] WARN at NametagEdit.jar//com.nametagedit.plugin.packets.PacketAccessor.<clinit>(PacketAccessor.java:85)
30.11 22:13:15 [Server] WARN at NametagEdit.jar//com.nametagedit.plugin.packets.PacketWrapper.<clinit>(PacketWrapper.java:27)
30.11 22:13:15 [Server] WARN at NametagEdit.jar//com.nametagedit.plugin.NametagEdit.testCompat(NametagEdit.java:90)
30.11 22:13:15 [Server] WARN at NametagEdit.jar//com.nametagedit.plugin.NametagEdit.onEnable(NametagEdit.java:40)
30.11 22:13:15 [Server] WARN at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264)
30.11 22:13:15 [Server] WARN at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:370)
30.11 22:13:15 [Server] WARN at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:500)
30.11 22:13:15 [Server] WARN at org.bukkit.craftbukkit.v1_18_R1.CraftServer.enablePlugin(CraftServer.java:565)
30.11 22:13:15 [Server] WARN at org.bukkit.craftbukkit.v1_18_R1.CraftServer.enablePlugins(CraftServer.java:479)
30.11 22:13:15 [Server] WARN at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:726)
30.11 22:13:15 [Server] WARN at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:501)
30.11 22:13:15 [Server] WARN at net.minecraft.server.dedicated.DedicatedServer.e(DedicatedServer.java:313)
30.11 22:13:15 [Server] WARN at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:1201)
30.11 22:13:15 [Server] WARN at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:316)
30.11 22:13:15 [Server] WARN at java.base/java.lang.Thread.run(Thread.java:833)
30.11 22:13:15 [Server] INFO [NametagEdit] Disabling NametagEdit v4.5.2
30.11 22:13:15 [Server] ERROR Error occurred while disabling NametagEdit v4.5.2 (Is it up to date?)
30.11 22:13:15 [Server] INFO java.lang.NullPointerException: Cannot invoke "com.nametagedit.plugin.NametagManager.reset()" because "this.manager" is null
30.11 22:13:15 [Server] INFO at com.nametagedit.plugin.NametagEdit.onDisable(NametagEdit.java:73) ~[NametagEdit.jar:?]
30.11 22:13:15 [Server] INFO at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:266) ~[paper-api-1.18-R0.1-SNAPSHOT.jar:?]
30.11 22:13:15 [Server] INFO at org.bukkit.plugin.java.JavaPluginLoader.disablePlugin(JavaPluginLoader.java:399) ~[paper-api-1.18-R0.1-SNAPSHOT.jar:?]
30.11 22:13:15 [Server] INFO at org.bukkit.plugin.SimplePluginManager.disablePlugin(SimplePluginManager.java:537) ~[paper-api-1.18-R0.1-SNAPSHOT.jar:?]
30.11 22:13:15 [Server] INFO at com.nametagedit.plugin.NametagEdit.testCompat(NametagEdit.java:93) ~[NametagEdit.jar:?]
30.11 22:13:15 [Server] INFO at com.nametagedit.plugin.NametagEdit.onEnable(NametagEdit.java:40) ~[NametagEdit.jar:?]
30.11 22:13:15 [Server] INFO at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264) ~[paper-api-1.18-R0.1-SNAPSHOT.jar:?]
30.11 22:13:15 [Server] INFO at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:370) ~[paper-api-1.18-R0.1-SNAPSHOT.jar:?]
30.11 22:13:15 [Server] INFO at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:500) ~[paper-api-1.18-R0.1-SNAPSHOT.jar:?]
30.11 22:13:15 [Server] INFO at org.bukkit.craftbukkit.v1_18_R1.CraftServer.enablePlugin(CraftServer.java:565) ~[paper-1.18.jar:git-Paper-11]
30.11 22:13:15 [Server] INFO at org.bukkit.craftbukkit.v1_18_R1.CraftServer.enablePlugins(CraftServer.java:479) ~[paper-1.18.jar:git-Paper-11]
30.11 22:13:15 [Server] INFO at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:726) ~[paper-1.18.jar:git-Paper-11]
30.11 22:13:15 [Server] INFO at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:501) ~[paper-1.18.jar:git-Paper-11]
30.11 22:13:15 [Server] INFO at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:313) ~[paper-1.18.jar:git-Paper-11]
30.11 22:13:15 [Server] INFO at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1201) ~[paper-1.18.jar:git-Paper-11]
30.11 22:13:15 [Server] INFO at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:316) ~[paper-1.18.jar:git-Paper-11]
30.11 22:13:15 [Server] INFO at java.lang.Thread.run(Thread.java:833) ~[?:?]
30.11 22:13:15 [Server] ERROR [NametagEdit] 
30.11 22:13:15 [Server] INFO ------------------------------------------------------
30.11 22:13:15 [Server] INFO [WARNING] NametagEdit v4.5.2 Failed to load! [WARNING]
30.11 22:13:15 [Server] INFO ------------------------------------------------------
30.11 22:13:15 [Server] INFO This might be an issue with reflection. REPORT this:
30.11 22:13:15 [Server] INFO Cannot invoke "java.lang.reflect.Field.set(Object, Object)" because "com.nametagedit.plugin.packets.PacketAccessor.PARAMS" is null
30.11 22:13:15 [Server] INFO The plugin will now self destruct.
30.11 22:13:15 [Server] INFO ------------------------------------------------------
```

Added in:

```
    v1_18("j", "b", "c", "i", "h", "g", "a", "f", "e", "d", "k");
```
- \src\main\java\com\nametagedit\plugin\packets\PacketData.java
- This might be incorrect and not sure how to retrieve it.

@Lorenzo0111 or @Aurelien30000 are you able to assist? Any help is appreciated. Hope this doesn't break older versions. :(

Using:
- https://github.com/sgtcaze/NametagEdit/tree/feature/1.18 as commits and then will merge to `staging` for testing.
- https://github.com/sgtcaze/NametagEdit/tree/staging

**Comment by Aurelien30000** [comment]
Method has been renamed, I have a fix for that, will fix it later today.

**Comment by Lorenzo0111** [comment]
Ok

**Comment by JustOneMoreBlock** [comment]
Thanks for taking a look. :)

**Comment by Aurelien30000** [comment]
Okay made a pr to fix the compatibility. Btw, some other things must be addressed, such as MVdW maven repo being down.
https://github.com/sgtcaze/NametagEdit/pull/674

**Comment by JustOneMoreBlock** [comment]
> 

Yeah, trying to get this resolved and then see if I or if you or @Lorenzo0111 don't mind assisting.

**Comment by JustOneMoreBlock** [comment]
I think the Hex Colors have broken again. :(

Look at https://github.com/sgtcaze/NametagEdit/commits/staging for all the changes I made. I do notice some references to `// 1.17`. But, doesn't seem to be anything specific to versioning though. It's just an `else` statement and anything after 1.17.x should use the code I would think.

This packet could be wrong.

```
 v1_18("j", "b", "c", "i", "h", "g", "a", "f", "e", "d", "k");
```
- Just copied from 1.17.x

**Comment by Aurelien30000** [comment]
Imo we should probably drop MVdW support, unfortunatetely.

**Comment by Aurelien30000** [comment]
> I think the Hex Colors have broken again. :(

Take a look here, you probably forgot the new case :D https://github.com/Aurelien30000/NametagEdit/commit/570802feba1154b4654e668a6cce884188893bf5#diff-ad46f6b6ad9ded7573401b10325898466deb033f81181408ba2c2867bea2e238R40

**Comment by Aurelien30000** [comment]
Fields seem okay, an error would be thrown otherwise iirc!

**Comment by Lorenzo0111** [comment]
> Imo we should probably drop MVdW support, unfortunatetely.

If you want I can host it in my maven repo so we can still use it

**Comment by JustOneMoreBlock** [comment]
Lol, I swear I added that. #677 

- Tested 1.18 (Works)
- Tested 1.8.x (Works)

https://www.spigotmc.org/threads/mvdwplaceholderapi.86664/page-19#post-4183130

Looks like they're using Clip PAPI in favor of Mvdw.

Might be best to drop it.

**Comment by unimatrixgit** [comment]
any fix yet?
still doesnt work

**Comment by Zosum** [comment]
Not sure Im new to GitHub.
But is there now a version that works on 1.18 or not <.<
I dont want to sound rude or anything like that but after I've read all these comments here, it sounds like there would be a solution.

**Comment by unimatrixgit** [comment]
After some digging i found the version that works. So first if your gona put 1.18 in your spigot page , upload the 1.18 jarfile to spigot and not keep the 1.17 one on there. The 1.18 Jar can be found here : https://ci.nametagedit.com/job/NametagEdit-Dev/

This works on papermc Latest experimental build 59. So im gona assume on spigot to as paper is a spigot fork.

**Comment by JustOneMoreBlock** [comment]
Yep, that works. Going to hopefully iron out some bugs before adding to the Spigot page.
