### ISSUE TITLE
ERROR

### ISSUE THREAD

**Issue by StealthDeci** [sgtcaze/NametagEdit#685]
[14:44:36 ERROR]: Error occurred while disabling NametagEdit v4.4.10 (Is it up to date?)
java.lang.NullPointerException: Cannot invoke "com.nametagedit.plugin.NametagManager.reset()" because "this.manager" is null
        at com.nametagedit.plugin.NametagEdit.onDisable(NametagEdit.java:73) ~[NametagEdit.jar:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:266) ~[purpur-api-1.18-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.plugin.java.JavaPluginLoader.disablePlugin(JavaPluginLoader.java:399) ~[purpur-api-1.18-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.plugin.SimplePluginManager.disablePlugin(SimplePluginManager.java:537) ~[purpur-api-1.18-R0.1-SNAPSHOT.jar:?]
        at com.nametagedit.plugin.NametagEdit.testCompat(NametagEdit.java:93) ~[NametagEdit.jar:?]
        at com.nametagedit.plugin.NametagEdit.onEnable(NametagEdit.java:40) ~[NametagEdit.jar:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264) ~[purpur-api-1.18-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:370) ~[purpur-api-1.18-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:500) ~[purpur-api-1.18-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.craftbukkit.v1_18_R1.CraftServer.enablePlugin(CraftServer.java:563) ~[purpur-1.18.jar:git-Purpur-1431]
        at org.bukkit.craftbukkit.v1_18_R1.CraftServer.enablePlugins(CraftServer.java:477) ~[purpur-1.18.jar:git-Purpur-1431]
        at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:730) ~[purpur-1.18.jar:git-Purpur-1431]
        at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:506) ~[purpur-1.18.jar:git-Purpur-1431]
        at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:347) ~[purpur-1.18.jar:git-Purpur-1431]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1215) ~[purpur-1.18.jar:git-Purpur-1431]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:320) ~[purpur-1.18.jar:git-Purpur-1431]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]
[14:44:36 ERROR]: [NametagEdit]
------------------------------------------------------
[WARNING] NametagEdit v4.4.10 Failed to load! [WARNING]
------------------------------------------------------
This might be an issue with reflection. REPORT this:
> Cannot invoke "java.lang.reflect.Constructor.newInstance(Object[])" because "com.nametagedit.plugin.packets.PacketWrapper.ChatComponentText" is null
The plugin will now self destruct.
------------------------------------------------------

**Comment by StealthDeci** [comment]
[17:12:01 WARN]: [NametagEdit] Task #4087 for NametagEdit v4.5.2 generated an exception
java.lang.NullPointerException: Cannot invoke "com.nametagedit.plugin.packets.VersionChecker$BukkitVersion.ordinal()" because the return value of "com.nametagedit.plugin.packets.VersionChecker.getBukkitVersion()" is null
        at com.nametagedit.plugin.utils.Utils.format(Utils.java:38) ~[NametagEdit头顶称号.jar:?]
        at com.nametagedit.plugin.NametagHandler.formatWithPlaceholders(NametagHandler.java:303) ~[NametagEdit头顶称号.jar:?]
        at com.nametagedit.plugin.NametagHandler$6.run(NametagHandler.java:391) ~[NametagEdit头顶称号.jar:?]
        at org.bukkit.craftbukkit.v1_18_R1.scheduler.CraftTask.run(CraftTask.java:101) ~[purpur-1.18.1.jar:git-Purpur-1444]
        at org.bukkit.craftbukkit.v1_18_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:483) ~[purpur-1.18.1.jar:git-Purpur-1444]
        at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1571) ~[purpur-1.18.1.jar:git-Purpur-1444]
        at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:516) ~[purpur-1.18.1.jar:git-Purpur-1444]
        at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1494) ~[purpur-1.18.1.jar:git-Purpur-1444]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1282) ~[purpur-1.18.1.jar:git-Purpur-1444]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:320) ~[purpur-1.18.1.jar:git-Purpur-1444]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]

**Comment by JustOneMoreBlock** [comment]
Please download the dev build here.
https://ci.nametagedit.com/job/NametagEdit-Dev/lastSuccessfulBuild/artifact/target/NametagEdit.jar
