### ISSUE TITLE
Tablist problems.

### ISSUE THREAD

**Issue by xJqlen** [sgtcaze/NametagEdit#69]
The plugin is great however there is one problem. The prefixes work with the players but then the don't show up in the tab. Please fix and I will give this plugin 5 stars but keep up the good work!

Plugins: I have AvdancedBan, AuctionHouse, Banknotes, Beast-XpWithDraw, ChatControl, CustomGUI, DeliveryMan, Duels, Envoys, Essentials, Factions, FlightParticles, KitAdder, LinkItem, Lores, Nametagedit, ObsidianDestroyer. PermissionsEX, PhoenixAntiCheat, PlayerVaults, PlugMan, ProtocolLib, RandomPackage_1.8, Staff+, StaffAndVipChat 2.7, StaffGUI, TimTheEnchanter_1.8, Vault, VoxelSniper, WorldEdit, WorldGuard, YouTube.

Version: Spigot 1.8.8

I am using the NameTagEdit groups.yml.

**Comment by JustOneMoreBlock** [comment]
If you're using groups.yml. Did you sort the groups by <highest to lowest> ?

Once that has been completed, Did you setup your permissions you created in NametagEdit in your permissions plugin?

If so, in the config.yml what's the tab list setting?

**Comment by xJqlen** [comment]
Yes I did all of that and set the tab list setting to true and false and nothing seem to work. Please help!

**Comment by JustOneMoreBlock** [comment]
Well, I tested the latest build 34 on Minecraft versions from 1.7.10 to 1.10.2, and the name above the name and the tab list works correctly.

The only thing I can think of it maybe a plugin interfering with NametagEdit.

**Comment by xJqlen** [comment]
Do you know what plugin could be interfering with it?

**Comment by xJqlen** [comment]
Here is what it says in the console after my server has loaded

[16:50:00] [Server thread/INFO]: [NametagEdit] Enabling NametagEdit v4.1.0
[16:50:00] [Server thread/ERROR]: Cannot load plugins\NametagEdit\groups.yml
org.bukkit.configuration.InvalidConfigurationException: while scanning for the next token
found character      '\t(TAB)' that cannot start any token. (Do not use \t(TAB) for indentation)
 in 'string', line 60, column 17:
        Suffix: '&f'  
                    ^

```
at org.bukkit.configuration.file.YamlConfiguration.loadFromString(YamlConfiguration.java:57) ~[spigot.jar:git-Spigot-db6de12-18fbb24]
at org.bukkit.configuration.file.FileConfiguration.load(FileConfiguration.java:226) ~[spigot.jar:git-Spigot-db6de12-18fbb24]
at org.bukkit.configuration.file.FileConfiguration.load(FileConfiguration.java:169) ~[spigot.jar:git-Spigot-db6de12-18fbb24]
at org.bukkit.configuration.file.YamlConfiguration.loadConfiguration(YamlConfiguration.java:180) [spigot.jar:git-Spigot-db6de12-18fbb24]
at com.nametagedit.plugin.utils.Utils.getConfig(Utils.java:114) [NametagEdit.jar:?]
at com.nametagedit.plugin.storage.flatfile.FlatFileConfig.load(FlatFileConfig.java:42) [NametagEdit.jar:?]
at com.nametagedit.plugin.NametagHandler.<init>(NametagHandler.java:51) [NametagEdit.jar:?]
at com.nametagedit.plugin.NametagEdit.onEnable(NametagEdit.java:30) [NametagEdit.jar:?]
at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:321) [spigot.jar:git-Spigot-db6de12-18fbb24]
at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:340) [spigot.jar:git-Spigot-db6de12-18fbb24]
at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:405) [spigot.jar:git-Spigot-db6de12-18fbb24]
at org.bukkit.craftbukkit.v1_8_R3.CraftServer.loadPlugin(CraftServer.java:357) [spigot.jar:git-Spigot-db6de12-18fbb24]
at org.bukkit.craftbukkit.v1_8_R3.CraftServer.enablePlugins(CraftServer.java:317) [spigot.jar:git-Spigot-db6de12-18fbb24]
at net.minecraft.server.v1_8_R3.MinecraftServer.s(MinecraftServer.java:414) [spigot.jar:git-Spigot-db6de12-18fbb24]
at net.minecraft.server.v1_8_R3.MinecraftServer.k(MinecraftServer.java:378) [spigot.jar:git-Spigot-db6de12-18fbb24]
at net.minecraft.server.v1_8_R3.MinecraftServer.a(MinecraftServer.java:333) [spigot.jar:git-Spigot-db6de12-18fbb24]
at net.minecraft.server.v1_8_R3.DedicatedServer.init(DedicatedServer.java:263) [spigot.jar:git-Spigot-db6de12-18fbb24]
at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:525) [spigot.jar:git-Spigot-db6de12-18fbb24]
at java.lang.Thread.run(Unknown Source) [?:1.8.0_92]
```

Caused by: org.yaml.snakeyaml.scanner.ScannerException: while scanning for the next token
found character      '\t(TAB)' that cannot start any token. (Do not use \t(TAB) for indentation)
 in 'string', line 60, column 17:
        Suffix: '&f'  
                    ^

```
at org.yaml.snakeyaml.scanner.ScannerImpl.fetchMoreTokens(ScannerImpl.java:420) ~[spigot.jar:git-Spigot-db6de12-18fbb24]
at org.yaml.snakeyaml.scanner.ScannerImpl.checkToken(ScannerImpl.java:226) ~[spigot.jar:git-Spigot-db6de12-18fbb24]
at org.yaml.snakeyaml.parser.ParserImpl$ParseBlockMappingKey.produce(ParserImpl.java:558) ~[spigot.jar:git-Spigot-db6de12-18fbb24]
at org.yaml.snakeyaml.parser.ParserImpl.peekEvent(ParserImpl.java:158) ~[spigot.jar:git-Spigot-db6de12-18fbb24]
at org.yaml.snakeyaml.parser.ParserImpl.checkEvent(ParserImpl.java:143) ~[spigot.jar:git-Spigot-db6de12-18fbb24]
at org.yaml.snakeyaml.composer.Composer.composeMappingNode(Composer.java:224) ~[spigot.jar:git-Spigot-db6de12-18fbb24]
at org.yaml.snakeyaml.composer.Composer.composeNode(Composer.java:155) ~[spigot.jar:git-Spigot-db6de12-18fbb24]
at org.yaml.snakeyaml.composer.Composer.composeMappingNode(Composer.java:229) ~[spigot.jar:git-Spigot-db6de12-18fbb24]
at org.yaml.snakeyaml.composer.Composer.composeNode(Composer.java:155) ~[spigot.jar:git-Spigot-db6de12-18fbb24]
at org.yaml.snakeyaml.composer.Composer.composeMappingNode(Composer.java:229) ~[spigot.jar:git-Spigot-db6de12-18fbb24]
at org.yaml.snakeyaml.composer.Composer.composeNode(Composer.java:155) ~[spigot.jar:git-Spigot-db6de12-18fbb24]
at org.yaml.snakeyaml.composer.Composer.composeDocument(Composer.java:122) ~[spigot.jar:git-Spigot-db6de12-18fbb24]
at org.yaml.snakeyaml.composer.Composer.getSingleNode(Composer.java:105) ~[spigot.jar:git-Spigot-db6de12-18fbb24]
at org.yaml.snakeyaml.constructor.BaseConstructor.getSingleData(BaseConstructor.java:120) ~[spigot.jar:git-Spigot-db6de12-18fbb24]
at org.yaml.snakeyaml.Yaml.loadFromReader(Yaml.java:450) ~[spigot.jar:git-Spigot-db6de12-18fbb24]
at org.yaml.snakeyaml.Yaml.load(Yaml.java:369) ~[spigot.jar:git-Spigot-db6de12-18fbb24]
at org.bukkit.configuration.file.YamlConfiguration.loadFromString(YamlConfiguration.java:55) ~[spigot.jar:git-Spigot-db6de12-18fbb24]
... 18 more
```

[16:50:00] [Server thread/ERROR]: Error occurred while enabling NametagEdit v4.1.0 (Is it up to date?)
java.lang.NullPointerException
    at com.nametagedit.plugin.storage.flatfile.FlatFileConfig.loadGroups(FlatFileConfig.java:133) ~[?:?]
    at com.nametagedit.plugin.storage.flatfile.FlatFileConfig.load(FlatFileConfig.java:45) ~[?:?]
    at com.nametagedit.plugin.NametagHandler.<init>(NametagHandler.java:51) ~[?:?]
    at com.nametagedit.plugin.NametagEdit.onEnable(NametagEdit.java:30) ~[?:?]
    at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:321) ~[spigot.jar:git-Spigot-db6de12-18fbb24]
    at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:340) [spigot.jar:git-Spigot-db6de12-18fbb24]
    at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:405) [spigot.jar:git-Spigot-db6de12-18fbb24]
    at org.bukkit.craftbukkit.v1_8_R3.CraftServer.loadPlugin(CraftServer.java:357) [spigot.jar:git-Spigot-db6de12-18fbb24]
    at org.bukkit.craftbukkit.v1_8_R3.CraftServer.enablePlugins(CraftServer.java:317) [spigot.jar:git-Spigot-db6de12-18fbb24]
    at net.minecraft.server.v1_8_R3.MinecraftServer.s(MinecraftServer.java:414) [spigot.jar:git-Spigot-db6de12-18fbb24]
    at net.minecraft.server.v1_8_R3.MinecraftServer.k(MinecraftServer.java:378) [spigot.jar:git-Spigot-db6de12-18fbb24]
    at net.minecraft.server.v1_8_R3.MinecraftServer.a(MinecraftServer.java:333) [spigot.jar:git-Spigot-db6de12-18fbb24]
    at net.minecraft.server.v1_8_R3.DedicatedServer.init(DedicatedServer.java:263) [spigot.jar:git-Spigot-db6de12-18fbb24]
    at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:525) [spigot.jar:git-Spigot-db6de12-18fbb24]
    at java.lang.Thread.run(Unknown

**Comment by sgtcaze** [comment]
@xJqlen Please post your groups.yml file, or input it into: http://yaml-online-parser.appspot.com/ to check the syntax

**Comment by xJqlen** [comment]
@sgtcaze 

Groups:
  Admin:
    Permission: nte.admin
    Prefix: '&4Admin'
    Suffix: '&f'
  Moderator:
    Permission: nte.moderator
    Prefix: '&3Mod'
    Suffix: '&f'
  Owner:
    Permission: nte.owner
    Prefix: '&5&lOwner'
    Suffix: '&5'
  Youtube:
    Permission: nte.youtube
    Prefix: '&cYou&fTube'
    Suffix: '&f'
  Twitch:
    Permission: nte.twitch
    Prefix: '&eTwitch'
    Suffix: '&f'
  Helper:
    Permission: nte.helper
    Prefix: '&dHelper'
  Default:
    Permission: nte.default
    Prefix: '&7Trainee'
    Suffix: '&f'
  Jr.Dev:
    Permission: nte.jrdev
    Prefix: '&cJr.Dev'
    Suffix: '&f'
  Dev:
    Permission: nte.dev
    Prefix: '&4Dev'
    Suffix: '&f'
  Captain:
    Permission: nte.captain
    Prefix: '&bCaptain'
    Suffix: '&f'
  Private:
    Permission: nte.priavte
    Prefix: '&aPrivate'
    Suffix: '&f'
  Commander:
    Permission: nte.commander
    Prefix: '&9Commander'
    Suffix: '&f'
  Admiral:
    Permission: nte.admiral
    Prefix: '&6Admiral'
    Suffix: '&f'
  General:
    Permission: nte.general
    Prefix: '&eGeneral'
    Suffix: '&f'
  Builder:
    Permission: nte.builder
    Prefix: '&2Builder'
    Suffix: '&f'

**Comment by sgtcaze** [comment]
@xJqlen Sorry for the delay didn't see the notification. Have you solved the issue? You posted a config that removed all the formatting, you'll want to use the yaml parser I linked above.

**Comment by sgtcaze** [comment]
No response in 5 days. Please reopen if the issue persists.
