### ISSUE TITLE
not loading

### ISSUE THREAD

**Issue by MatthijsvandenBo** [sgtcaze/NametagEdit#702]
[18:28:39 INFO]: [NametagEdit] Disabling NametagEdit v4.4.10
[18:28:39 ERROR]: Error occurred while disabling NametagEdit v4.4.10 (Is it up to date?)
java.lang.NullPointerException: Cannot invoke "com.nametagedit.plugin.NametagManager.reset()" because "this.manager" is null
at com.nametagedit.plugin.NametagEdit.onDisable(NametagEdit.java:73) ~[NametagEdit.jar:?]
at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:266) ~[purpur-api-1.18.1-R0.1-SNAPSHOT.jar:?]
at org.bukkit.plugin.java.JavaPluginLoader.disablePlugin(JavaPluginLoader.java:399) ~[purpur-api-1.18.1-R0.1-SNAPSHOT.jar:?]
at org.bukkit.plugin.SimplePluginManager.disablePlugin(SimplePluginManager.java:537) ~[purpur-api-1.18.1-R0.1-SNAPSHOT.jar:?]
at com.nametagedit.plugin.NametagEdit.testCompat(NametagEdit.java:93) ~[NametagEdit.jar:?]
at com.nametagedit.plugin.NametagEdit.onEnable(NametagEdit.java:40) ~[NametagEdit.jar:?]
at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264) ~[purpur-api-1.18.1-R0.1-SNAPSHOT.jar:?]
at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:370) ~[purpur-api-1.18.1-R0.1-SNAPSHOT.jar:?]
at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:500) ~[purpur-api-1.18.1-R0.1-SNAPSHOT.jar:?]
at org.bukkit.craftbukkit.v1_18_R1.CraftServer.enablePlugin(CraftServer.java:563) ~[purpur-1.18.1.jar:git-Purpur-1436]
at org.bukkit.craftbukkit.v1_18_R1.CraftServer.enablePlugins(CraftServer.java:477) ~[purpur-1.18.1.jar:git-Purpur-1436]
at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:730) ~[purpur-1.18.1.jar:git-Purpur-1436]
at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:506) ~[purpur-1.18.1.jar:git-Purpur-1436]
at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:347) ~[purpur-1.18.1.jar:git-Purpur-1436]
at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1215) ~[purpur-1.18.1.jar:git-Purpur-1436]
at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:320) ~[purpur-1.18.1.jar:git-Purpur-1436]
at java.lang.Thread.run(Thread.java:833) ~[?:?]
[18:28:39 ERROR]: [NametagEdit]
------------------------------------------------------
[WARNING] NametagEdit v4.4.10 Failed to load! [WARNING]
------------------------------------------------------
This might be an issue with reflection. REPORT this:
> Cannot invoke "java.lang.reflect.Constructor.newInstance(Object[])" because "com.nametagedit.plugin.packets.PacketWrapper.ChatComponentText" is null
The plugin will now self destruct.
------------------------------------------------------

**Comment by Arqsz** [comment]
Getting the same error with the newest version on Paper 1.18.1.

**Comment by JustOneMoreBlock** [comment]
https://ci.nametagedit.com/job/NametagEdit-Dev/lastSuccessfulBuild/artifact/target/NametagEdit.jar
