### ISSUE TITLE
Error (last Paper 1.18.1)

### ISSUE THREAD

**Issue by moda84** [sgtcaze/NametagEdit#704]
[16:52:18 INFO]: [NametagEdit] Enabling NametagEdit v4.5.0
[16:52:18 WARN]: java.lang.NoSuchMethodException: net.minecraft.server.network.PlayerConnection.sendPacket(net.minecraft.network.protocol.Packet)
[16:52:18 WARN]: 	at java.base/java.lang.Class.getMethod(Class.java:2227)
[16:52:18 WARN]: 	at NametagEdit (1).jar//com.nametagedit.plugin.packets.PacketAccessor.(PacketAccessor.java:85)
[16:52:18 WARN]: 	at NametagEdit (1).jar//com.nametagedit.plugin.packets.PacketWrapper.(PacketWrapper.java:27)
[16:52:18 WARN]: 	at NametagEdit (1).jar//com.nametagedit.plugin.NametagEdit.testCompat(NametagEdit.java:90)
[16:52:18 WARN]: 	at NametagEdit (1).jar//com.nametagedit.plugin.NametagEdit.onEnable(NametagEdit.java:40)
[16:52:18 WARN]: 	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264)
[16:52:18 WARN]: 	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:370)
[16:52:18 WARN]: 	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:500)
[16:52:18 WARN]: 	at org.bukkit.craftbukkit.v1_18_R1.CraftServer.enablePlugin(CraftServer.java:564)
[16:52:18 WARN]: 	at org.bukkit.craftbukkit.v1_18_R1.CraftServer.enablePlugins(CraftServer.java:478)
[16:52:18 WARN]: 	at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:727)
[16:52:18 WARN]: 	at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:503)
[16:52:18 WARN]: 	at net.minecraft.server.dedicated.DedicatedServer.e(DedicatedServer.java:313)
[16:52:18 WARN]: 	at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:1202)
[16:52:18 WARN]: 	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:317)
[16:52:18 WARN]: 	at java.base/java.lang.Thread.run(Thread.java:833)
[16:52:18 INFO]: [NametagEdit] Disabling NametagEdit v4.5.0
[16:52:18 ERROR]: Error occurred while disabling NametagEdit v4.5.0 (Is it up to date?)
java.lang.NullPointerException: Cannot invoke "com.nametagedit.plugin.NametagManager.reset()" because "this.manager" is null
	at com.nametagedit.plugin.NametagEdit.onDisable(NametagEdit.java:73) ~[NametagEdit (1).jar:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:266) ~[paper-api-1.18.1-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.plugin.java.JavaPluginLoader.disablePlugin(JavaPluginLoader.java:399) ~[paper-api-1.18.1-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.plugin.SimplePluginManager.disablePlugin(SimplePluginManager.java:537) ~[paper-api-1.18.1-R0.1-SNAPSHOT.jar:?]
	at com.nametagedit.plugin.NametagEdit.testCompat(NametagEdit.java:93) ~[NametagEdit (1).jar:?]
	at com.nametagedit.plugin.NametagEdit.onEnable(NametagEdit.java:40) ~[NametagEdit (1).jar:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264) ~[paper-api-1.18.1-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:370) ~[paper-api-1.18.1-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:500) ~[paper-api-1.18.1-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.craftbukkit.v1_18_R1.CraftServer.enablePlugin(CraftServer.java:564) ~[paper-1.18.1.jar:git-Paper-134]
	at org.bukkit.craftbukkit.v1_18_R1.CraftServer.enablePlugins(CraftServer.java:478) ~[paper-1.18.1.jar:git-Paper-134]
	at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:727) ~[paper-1.18.1.jar:git-Paper-134]
	at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:503) ~[paper-1.18.1.jar:git-Paper-134]
	at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:313) ~[paper-1.18.1.jar:git-Paper-134]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1202) ~[paper-1.18.1.jar:git-Paper-134]
	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:317) ~[paper-1.18.1.jar:git-Paper-134]
	at java.lang.Thread.run(Thread.java:833) ~[?:?]
[16:52:18 ERROR]: [NametagEdit] 
------------------------------------------------------
[WARNING] NametagEdit v4.5.0 Failed to load! [WARNING]
------------------------------------------------------
This might be an issue with reflection. REPORT this:
> Cannot invoke "java.lang.reflect.Field.set(Object, Object)" because "com.nametagedit.plugin.packets.PacketAccessor.PARAMS" is null
The plugin will now self destruct.
------------------------------------------------------

**Comment by LemonsHQ** [comment]
Same error here using the latest Paper version!

**Comment by JssJeet** [comment]
Same error

**Comment by Maaattqc** [comment]
same

**Comment by xMrOxy** [comment]
same

**Comment by JustOneMoreBlock** [comment]
https://ci.nametagedit.com/job/NametagEdit-Dev/lastSuccessfulBuild/artifact/target/NametagEdit.jar
