### ISSUE TITLE
Issue with NtE MC 1.18.1 / v4.4.10

### ISSUE THREAD

**Issue by PlayingWithPi** [sgtcaze/NametagEdit#713]
# Bug Report

**Type /ver NametagEdit and post the output.**
4.4.10

**What version of Bukkit/Spigot/PaperSpigot are you using? Type /ver**
28.01 23:31:24 [Server] INFO Checking version, please wait...
28.01 23:31:24 [Server] INFO This server is running Paper version git-Paper-175 (MC: 1.18.1) (Implementing API version 1.18.1-R0.1-SNAPSHOT) (Git: 9490475)
28.01 23:31:24 [Server] INFO You are 2 version(s) behind
28.01 23:31:24 [Server] INFO Download the new version at: https://papermc.io/downloads
28.01 23:31:24 [Server] INFO Previous version: git-Paper-164 (MC: 1.18.1)

**What plugins are you using? Type /plugins**
```
[Server] INFO Plugins (47): AcceptTheRules, AdvancedAchievements, AdvancedReplay*, AntiCheatReplay, ArmorStandTools, BuycraftX, ChestShop, ChestShopNotifier, ClearLag, CommandSigns, ConsoleSpamFix, CoreProtect, CraftBook, CrateReloaded, DiscordSRV, dynmap, Essentials, EssentialsSpawn, Herochat*, HolographicDisplays, KeepDeathDrop, LibsDisguises, LiteBans, LuckPerms, Maintenance, mcMMO, MobArena, MyWarp, NametagEdit*, OpenInv, OreAnnouncer, OreAnnouncerGUI, PlaceholderAPI, ProtectionStones, ProtocolLib, SuperVanish, Vault, ViaBackwards, ViaVersion, Votifier, VotingPlugin, Vulcan, WGEF-Reborn, WorldBorder, WorldEdit, WorldEditSelectionVisualizer, WorldGuard
```

**Please explain your issue. How do you trigger it?**
Add plugin, rerstart server

**Are there any errors in the console? Please use: https://pastebin.com**
```
28.01 23:27:36 [Server] INFO [NametagEdit] Enabling NametagEdit v4.4.10*
28.01 23:27:36 [Server] WARN java.lang.ClassNotFoundException: net.minecraft.server.v1_18_R1.PacketPlayOutScoreboardTeam
28.01 23:27:36 [Server] WARN at org.bukkit.plugin.java.PluginClassLoader.loadClass0(PluginClassLoader.java:151)
28.01 23:27:36 [Server] WARN at org.bukkit.plugin.java.PluginClassLoader.loadClass(PluginClassLoader.java:103)
28.01 23:27:36 [Server] WARN at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:520)
28.01 23:27:36 [Server] WARN at java.base/java.lang.Class.forName0(Native Method)
28.01 23:27:36 [Server] WARN at java.base/java.lang.Class.forName(Class.java:375)
28.01 23:27:36 [Server] WARN at NametagEdit.jar//com.nametagedit.plugin.packets.PacketAccessor.<clinit>(PacketAccessor.java:59)
28.01 23:27:36 [Server] WARN at NametagEdit.jar//com.nametagedit.plugin.packets.PacketWrapper.<clinit>(PacketWrapper.java:25)
28.01 23:27:36 [Server] WARN at NametagEdit.jar//com.nametagedit.plugin.NametagEdit.testCompat(NametagEdit.java:90)
28.01 23:27:36 [Server] WARN at NametagEdit.jar//com.nametagedit.plugin.NametagEdit.onEnable(NametagEdit.java:40)
28.01 23:27:36 [Server] WARN at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264)
28.01 23:27:36 [Server] WARN at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:370)
28.01 23:27:36 [Server] WARN at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:500)
28.01 23:27:36 [Server] WARN at org.bukkit.craftbukkit.v1_18_R1.CraftServer.enablePlugin(CraftServer.java:564)
28.01 23:27:36 [Server] WARN at org.bukkit.craftbukkit.v1_18_R1.CraftServer.enablePlugins(CraftServer.java:478)
28.01 23:27:36 [Server] WARN at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:727)
28.01 23:27:36 [Server] WARN at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:503)
28.01 23:27:36 [Server] WARN at net.minecraft.server.dedicated.DedicatedServer.e(DedicatedServer.java:313)
28.01 23:27:36 [Server] WARN at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:1202)
28.01 23:27:36 [Server] WARN at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:317)
28.01 23:27:36 [Server] WARN at java.base/java.lang.Thread.run(Thread.java:833)
28.01 23:27:36 [Server] WARN java.lang.ClassNotFoundException: net.minecraft.server.v1_18_R1.ChatComponentText
28.01 23:27:36 [Server] WARN at org.bukkit.plugin.java.PluginClassLoader.loadClass0(PluginClassLoader.java:151)
28.01 23:27:36 [Server] WARN at org.bukkit.plugin.java.PluginClassLoader.loadClass(PluginClassLoader.java:103)
28.01 23:27:36 [Server] WARN at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:520)
28.01 23:27:36 [Server] WARN at java.base/java.lang.Class.forName0(Native Method)
28.01 23:27:36 [Server] WARN at java.base/java.lang.Class.forName(Class.java:375)
28.01 23:27:36 [Server] WARN at NametagEdit.jar//com.nametagedit.plugin.packets.PacketWrapper.<clinit>(PacketWrapper.java:28)
28.01 23:27:36 [Server] WARN at NametagEdit.jar//com.nametagedit.plugin.NametagEdit.testCompat(NametagEdit.java:90)
28.01 23:27:36 [Server] WARN at NametagEdit.jar//com.nametagedit.plugin.NametagEdit.onEnable(NametagEdit.java:40)
28.01 23:27:36 [Server] WARN at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264)
28.01 23:27:36 [Server] WARN at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:370)
28.01 23:27:36 [Server] WARN at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:500)
28.01 23:27:36 [Server] WARN at org.bukkit.craftbukkit.v1_18_R1.CraftServer.enablePlugin(CraftServer.java:564)
28.01 23:27:36 [Server] WARN at org.bukkit.craftbukkit.v1_18_R1.CraftServer.enablePlugins(CraftServer.java:478)
28.01 23:27:36 [Server] WARN at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:727)
28.01 23:27:36 [Server] WARN at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:503)
28.01 23:27:36 [Server] WARN at net.minecraft.server.dedicated.DedicatedServer.e(DedicatedServer.java:313)
28.01 23:27:36 [Server] WARN at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:1202)
28.01 23:27:36 [Server] WARN at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:317)
28.01 23:27:36 [Server] WARN at java.base/java.lang.Thread.run(Thread.java:833)
28.01 23:27:36 [Server] WARN java.lang.NullPointerException: Cannot invoke "java.lang.Class.newInstance()" because "com.nametagedit.plugin.packets.PacketAccessor.packetClass" is null
28.01 23:27:36 [Server] WARN at NametagEdit.jar//com.nametagedit.plugin.packets.PacketAccessor.createPacket(PacketAccessor.java:123)
28.01 23:27:36 [Server] WARN at NametagEdit.jar//com.nametagedit.plugin.packets.PacketWrapper.<init>(PacketWrapper.java:18)
28.01 23:27:36 [Server] WARN at NametagEdit.jar//com.nametagedit.plugin.NametagEdit.testCompat(NametagEdit.java:90)
28.01 23:27:36 [Server] WARN at NametagEdit.jar//com.nametagedit.plugin.NametagEdit.onEnable(NametagEdit.java:40)
28.01 23:27:36 [Server] WARN at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264)
28.01 23:27:36 [Server] WARN at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:370)
28.01 23:27:36 [Server] WARN at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:500)
28.01 23:27:36 [Server] WARN at org.bukkit.craftbukkit.v1_18_R1.CraftServer.enablePlugin(CraftServer.java:564)
28.01 23:27:36 [Server] WARN at org.bukkit.craftbukkit.v1_18_R1.CraftServer.enablePlugins(CraftServer.java:478)
28.01 23:27:36 [Server] WARN at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:727)
28.01 23:27:36 [Server] WARN at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:503)
28.01 23:27:36 [Server] WARN at net.minecraft.server.dedicated.DedicatedServer.e(DedicatedServer.java:313)
28.01 23:27:36 [Server] WARN at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:1202)
28.01 23:27:36 [Server] WARN at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:317)
28.01 23:27:36 [Server] WARN at java.base/java.lang.Thread.run(Thread.java:833)
28.01 23:27:36 [Server] INFO [NametagEdit] Disabling NametagEdit v4.4.10
28.01 23:27:36 [Server] ERROR Error occurred while disabling NametagEdit v4.4.10 (Is it up to date?)
28.01 23:27:36 [Server] INFO java.lang.NullPointerException: Cannot invoke "com.nametagedit.plugin.NametagManager.reset()" because "this.manager" is null
28.01 23:27:36 [Server] INFO at com.nametagedit.plugin.NametagEdit.onDisable(NametagEdit.java:73) ~[NametagEdit.jar:?]
28.01 23:27:36 [Server] INFO at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:266) ~[paper-api-1.18.1-R0.1-SNAPSHOT.jar:?]
28.01 23:27:36 [Server] INFO at org.bukkit.plugin.java.JavaPluginLoader.disablePlugin(JavaPluginLoader.java:399) ~[paper-api-1.18.1-R0.1-SNAPSHOT.jar:?]
28.01 23:27:36 [Server] INFO at org.bukkit.plugin.SimplePluginManager.disablePlugin(SimplePluginManager.java:537) ~[paper-api-1.18.1-R0.1-SNAPSHOT.jar:?]
28.01 23:27:36 [Server] INFO at com.nametagedit.plugin.NametagEdit.testCompat(NametagEdit.java:93) ~[NametagEdit.jar:?]
28.01 23:27:36 [Server] INFO at com.nametagedit.plugin.NametagEdit.onEnable(NametagEdit.java:40) ~[NametagEdit.jar:?]
28.01 23:27:36 [Server] INFO at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264) ~[paper-api-1.18.1-R0.1-SNAPSHOT.jar:?]
28.01 23:27:36 [Server] INFO at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:370) ~[paper-api-1.18.1-R0.1-SNAPSHOT.jar:?]
28.01 23:27:36 [Server] INFO at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:500) ~[paper-api-1.18.1-R0.1-SNAPSHOT.jar:?]
28.01 23:27:36 [Server] INFO at org.bukkit.craftbukkit.v1_18_R1.CraftServer.enablePlugin(CraftServer.java:564) ~[paper-1.18.1.jar:git-Paper-175]
28.01 23:27:36 [Server] INFO at org.bukkit.craftbukkit.v1_18_R1.CraftServer.enablePlugins(CraftServer.java:478) ~[paper-1.18.1.jar:git-Paper-175]
28.01 23:27:36 [Server] INFO at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:727) ~[paper-1.18.1.jar:git-Paper-175]
28.01 23:27:36 [Server] INFO at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:503) ~[paper-1.18.1.jar:git-Paper-175]
28.01 23:27:36 [Server] INFO at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:313) ~[paper-1.18.1.jar:git-Paper-175]
28.01 23:27:36 [Server] INFO at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1202) ~[paper-1.18.1.jar:git-Paper-175]
28.01 23:27:36 [Server] INFO at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:317) ~[paper-1.18.1.jar:git-Paper-175]
28.01 23:27:36 [Server] INFO at java.lang.Thread.run(Thread.java:833) ~[?:?]
28.01 23:27:36 [Server] ERROR [NametagEdit] 
28.01 23:27:36 [Server] INFO ------------------------------------------------------
28.01 23:27:36 [Server] INFO [WARNING] NametagEdit v4.4.10 Failed to load! [WARNING]
28.01 23:27:36 [Server] INFO ------------------------------------------------------
28.01 23:27:36 [Server] INFO This might be an issue with reflection. REPORT this:
28.01 23:27:36 [Server] INFO Cannot invoke "java.lang.reflect.Constructor.newInstance(Object[])" because "com.nametagedit.plugin.packets.PacketWrapper.ChatComponentText" is null
28.01 23:27:36 [Server] INFO The plugin will now self destruct.
28.01 23:27:36 [Server] INFO ------------------------------------------------------
```

**Comment by PlayingWithPi** [comment]
attempted with NtE v 4.5.0

```log
28.01 23:45:28 [Server] ERROR [NametagEdit] 
28.01 23:45:28 [Server] INFO ------------------------------------------------------
28.01 23:45:28 [Server] INFO [WARNING] NametagEdit v4.5.0 Failed to load! [WARNING]
28.01 23:45:28 [Server] INFO ------------------------------------------------------
28.01 23:45:28 [Server] INFO This might be an issue with reflection. REPORT this:
28.01 23:45:28 [Server] INFO Cannot invoke "java.lang.reflect.Field.set(Object, Object)" because "com.nametagedit.plugin.packets.PacketAccessor.PARAMS" is null
28.01 23:45:28 [Server] INFO The plugin will now self destruct.
```

**Comment by JustOneMoreBlock** [comment]
Use https://ci.nametagedit.com/job/NametagEdit-Dev/lastSuccessfulBuild/artifact/target/NametagEdit.jar
