### ISSUE TITLE
the plugin isnt activating in 1.18.1 downloaded from spigotmc and update the jar in spigotmc too

### ISSUE THREAD

**Issue by priyam1234-spec** [sgtcaze/NametagEdit#725]
the error 
[16:39:14] [Server thread/INFO]: [NametagEdit] Enabling NametagEdit v4.4.10*
--
186 | [16:39:14] [Server thread/WARN]: java.lang.ClassNotFoundException: net.minecraft.server.v1_18_R1.PacketPlayOutScoreboardTeam
187 | [16:39:14] [Server thread/WARN]: 	at org.bukkit.plugin.java.PluginClassLoader.loadClass0(PluginClassLoader.java:151)
188 | [16:39:14] [Server thread/WARN]: 	at org.bukkit.plugin.java.PluginClassLoader.loadClass(PluginClassLoader.java:103)
189 | [16:39:14] [Server thread/WARN]: 	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:520)
190 | [16:39:14] [Server thread/WARN]: 	at java.base/java.lang.Class.forName0(Native Method)
191 | [16:39:14] [Server thread/WARN]: 	at java.base/java.lang.Class.forName(Class.java:375)
192 | [16:39:14] [Server thread/WARN]: 	at NametagEdit.jar//com.nametagedit.plugin.packets.PacketAccessor.<clinit>(PacketAccessor.java:59)
193 | [16:39:14] [Server thread/WARN]: 	at NametagEdit.jar//com.nametagedit.plugin.packets.PacketWrapper.<clinit>(PacketWrapper.java:25)
194 | [16:39:14] [Server thread/WARN]: 	at NametagEdit.jar//com.nametagedit.plugin.NametagEdit.testCompat(NametagEdit.java:90)
195 | [16:39:14] [Server thread/WARN]: 	at NametagEdit.jar//com.nametagedit.plugin.NametagEdit.onEnable(NametagEdit.java:40)
196 | [16:39:14] [Server thread/WARN]: 	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264)
197 | [16:39:14] [Server thread/WARN]: 	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:370)
198 | [16:39:14] [Server thread/WARN]: 	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:501)
199 | [16:39:14] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_18_R1.CraftServer.enablePlugin(CraftServer.java:562)
200 | [16:39:14] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_18_R1.CraftServer.enablePlugins(CraftServer.java:476)
201 | [16:39:14] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:736)
202 | [16:39:14] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:503)
203 | [16:39:14] [Server thread/WARN]: 	at net.minecraft.server.dedicated.DedicatedServer.e(DedicatedServer.java:313)
204 | [16:39:14] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:1211)
205 | [16:39:14] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:317)
206 | [16:39:14] [Server thread/WARN]: 	at java.base/java.lang.Thread.run(Thread.java:833)
207 | [16:39:14] [Server thread/WARN]: java.lang.ClassNotFoundException: net.minecraft.server.v1_18_R1.ChatComponentText
208 | [16:39:14] [Server thread/WARN]: 	at org.bukkit.plugin.java.PluginClassLoader.loadClass0(PluginClassLoader.java:151)
209 | [16:39:14] [Server thread/WARN]: 	at org.bukkit.plugin.java.PluginClassLoader.loadClass(PluginClassLoader.java:103)
210 | [16:39:14] [Server thread/WARN]: 	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:520)
211 | [16:39:14] [Server thread/WARN]: 	at java.base/java.lang.Class.forName0(Native Method)
212 | [16:39:14] [Server thread/WARN]: 	at java.base/java.lang.Class.forName(Class.java:375)
213 | [16:39:14] [Server thread/WARN]: 	at NametagEdit.jar//com.nametagedit.plugin.packets.PacketWrapper.<clinit>(PacketWrapper.java:28)
214 | [16:39:14] [Server thread/WARN]: 	at NametagEdit.jar//com.nametagedit.plugin.NametagEdit.testCompat(NametagEdit.java:90)
215 | [16:39:14] [Server thread/WARN]: 	at NametagEdit.jar//com.nametagedit.plugin.NametagEdit.onEnable(NametagEdit.java:40)
216 | [16:39:14] [Server thread/WARN]: 	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264)
217 | [16:39:14] [Server thread/WARN]: 	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:370)
218 | [16:39:14] [Server thread/WARN]: 	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:501)
219 | [16:39:14] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_18_R1.CraftServer.enablePlugin(CraftServer.java:562)
220 | [16:39:14] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_18_R1.CraftServer.enablePlugins(CraftServer.java:476)
221 | [16:39:14] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:736)
222 | [16:39:14] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:503)
223 | [16:39:14] [Server thread/WARN]: 	at net.minecraft.server.dedicated.DedicatedServer.e(DedicatedServer.java:313)
224 | [16:39:14] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:1211)
225 | [16:39:14] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:317)
226 | [16:39:14] [Server thread/WARN]: 	at java.base/java.lang.Thread.run(Thread.java:833)
227 | [16:39:14] [Server thread/WARN]: java.lang.NullPointerException: Cannot invoke "java.lang.Class.newInstance()" because "com.nametagedit.plugin.packets.PacketAccessor.packetClass" is null
228 | [16:39:14] [Server thread/WARN]: 	at NametagEdit.jar//com.nametagedit.plugin.packets.PacketAccessor.createPacket(PacketAccessor.java:123)
229 | [16:39:14] [Server thread/WARN]: 	at NametagEdit.jar//com.nametagedit.plugin.packets.PacketWrapper.<init>(PacketWrapper.java:18)
230 | [16:39:14] [Server thread/WARN]: 	at NametagEdit.jar//com.nametagedit.plugin.NametagEdit.testCompat(NametagEdit.java:90)
231 | [16:39:14] [Server thread/WARN]: 	at NametagEdit.jar//com.nametagedit.plugin.NametagEdit.onEnable(NametagEdit.java:40)
232 | [16:39:14] [Server thread/WARN]: 	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264)
233 | [16:39:14] [Server thread/WARN]: 	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:370)
234 | [16:39:14] [Server thread/WARN]: 	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:501)
235 | [16:39:14] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_18_R1.CraftServer.enablePlugin(CraftServer.java:562)
236 | [16:39:14] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_18_R1.CraftServer.enablePlugins(CraftServer.java:476)
237 | [16:39:14] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:736)
238 | [16:39:14] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:503)
239 | [16:39:14] [Server thread/WARN]: 	at net.minecraft.server.dedicated.DedicatedServer.e(DedicatedServer.java:313)
240 | [16:39:14] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:1211)
241 | [16:39:14] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:317)
242 | [16:39:14] [Server thread/WARN]: 	at java.base/java.lang.Thread.run(Thread.java:833)
243 | [16:39:14] [Server thread/INFO]: [NametagEdit] Disabling NametagEdit v4.4.10
244 | [16:39:14] [Server thread/ERROR]: Error occurred while disabling NametagEdit v4.4.10 (Is it up to date?)
245 | java.lang.NullPointerException: Cannot invoke "com.nametagedit.plugin.NametagManager.reset()" because "this.manager" is null
246 | at com.nametagedit.plugin.NametagEdit.onDisable(NametagEdit.java:73) ~[NametagEdit.jar:?]
247 | at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:266) ~[paper-api-1.18.1-R0.1-SNAPSHOT.jar:?]
248 | at org.bukkit.plugin.java.JavaPluginLoader.disablePlugin(JavaPluginLoader.java:399) ~[paper-api-1.18.1-R0.1-SNAPSHOT.jar:?]
249 | at org.bukkit.plugin.SimplePluginManager.disablePlugin(SimplePluginManager.java:538) ~[paper-api-1.18.1-R0.1-SNAPSHOT.jar:?]
250 | at com.nametagedit.plugin.NametagEdit.testCompat(NametagEdit.java:93) ~[NametagEdit.jar:?]
251 | at com.nametagedit.plugin.NametagEdit.onEnable(NametagEdit.java:40) ~[NametagEdit.jar:?]
252 | at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264) ~[paper-api-1.18.1-R0.1-SNAPSHOT.jar:?]
253 | at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:370) ~[paper-api-1.18.1-R0.1-SNAPSHOT.jar:?]
254 | at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:501) ~[paper-api-1.18.1-R0.1-SNAPSHOT.jar:?]
255 | at org.bukkit.craftbukkit.v1_18_R1.CraftServer.enablePlugin(CraftServer.java:562) ~[paper-1.18.1.jar:git-Paper-215]
256 | at org.bukkit.craftbukkit.v1_18_R1.CraftServer.enablePlugins(CraftServer.java:476) ~[paper-1.18.1.jar:git-Paper-215]
257 | at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:736) ~[paper-1.18.1.jar:git-Paper-215]
258 | at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:503) ~[paper-1.18.1.jar:git-Paper-215]
259 | at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:313) ~[paper-1.18.1.jar:git-Paper-215]
260 | at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1211) ~[paper-1.18.1.jar:git-Paper-215]
261 | at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:317) ~[paper-1.18.1.jar:git-Paper-215]
262 | at java.lang.Thread.run(Thread.java:833) ~[?:?]
263 | [16:39:14] [Server thread/ERROR]: [NametagEdit]
264 | ------------------------------------------------------
265 | [WARNING] NametagEdit v4.4.10 Failed to load! [WARNING]
266 | ------------------------------------------------------
267 | This might be an issue with reflection. REPORT this:
268 | > Cannot invoke "java.lang.reflect.Constructor.newInstance(Object[])" because "com.nametagedit.plugin.packets.PacketWrapper.ChatComponentText" is null
269 | The plugin will now self destruct.
270 | ------------------------------------------------------

</body>
</html>[16:39:14] [Server thread/INFO]: [NametagEdit] Enabling NametagEdit v4.4.10*
[16:39:14] [Server thread/WARN]: java.lang.ClassNotFoundException: net.minecraft.server.v1_18_R1.PacketPlayOutScoreboardTeam
[16:39:14] [Server thread/WARN]: 	at org.bukkit.plugin.java.PluginClassLoader.loadClass0(PluginClassLoader.java:151)
[16:39:14] [Server thread/WARN]: 	at org.bukkit.plugin.java.PluginClassLoader.loadClass(PluginClassLoader.java:103)
[16:39:14] [Server thread/WARN]: 	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:520)
[16:39:14] [Server thread/WARN]: 	at java.base/java.lang.Class.forName0(Native Method)
[16:39:14] [Server thread/WARN]: 	at java.base/java.lang.Class.forName(Class.java:375)
[16:39:14] [Server thread/WARN]: 	at NametagEdit.jar//com.nametagedit.plugin.packets.PacketAccessor.<clinit>(PacketAccessor.java:59)
[16:39:14] [Server thread/WARN]: 	at NametagEdit.jar//com.nametagedit.plugin.packets.PacketWrapper.<clinit>(PacketWrapper.java:25)
[16:39:14] [Server thread/WARN]: 	at NametagEdit.jar//com.nametagedit.plugin.NametagEdit.testCompat(NametagEdit.java:90)
[16:39:14] [Server thread/WARN]: 	at NametagEdit.jar//com.nametagedit.plugin.NametagEdit.onEnable(NametagEdit.java:40)
[16:39:14] [Server thread/WARN]: 	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264)
[16:39:14] [Server thread/WARN]: 	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:370)
[16:39:14] [Server thread/WARN]: 	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:501)
[16:39:14] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_18_R1.CraftServer.enablePlugin(CraftServer.java:562)
[16:39:14] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_18_R1.CraftServer.enablePlugins(CraftServer.java:476)
[16:39:14] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:736)
[16:39:14] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:503)
[16:39:14] [Server thread/WARN]: 	at net.minecraft.server.dedicated.DedicatedServer.e(DedicatedServer.java:313)
[16:39:14] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:1[211](https://aternos.org/log/#L211))
[16:39:14] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:317)
[16:39:14] [Server thread/WARN]: 	at java.base/java.lang.Thread.run(Thread.java:833)
[16:39:14] [Server thread/WARN]: java.lang.ClassNotFoundException: net.minecraft.server.v1_18_R1.ChatComponentText
[16:39:14] [Server thread/WARN]: 	at org.bukkit.plugin.java.PluginClassLoader.loadClass0(PluginClassLoader.java:151)
[16:39:14] [Server thread/WARN]: 	at org.bukkit.plugin.java.PluginClassLoader.loadClass(PluginClassLoader.java:103)
[16:39:14] [Server thread/WARN]: 	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:520)
[16:39:14] [Server thread/WARN]: 	at java.base/java.lang.Class.forName0(Native Method)
[16:39:14] [Server thread/WARN]: 	at java.base/java.lang.Class.forName(Class.java:375)
[16:39:14] [Server thread/WARN]: 	at NametagEdit.jar//com.nametagedit.plugin.packets.PacketWrapper.<clinit>(PacketWrapper.java:28)
[16:39:14] [Server thread/WARN]: 	at NametagEdit.jar//com.nametagedit.plugin.NametagEdit.testCompat(NametagEdit.java:90)
[16:39:14] [Server thread/WARN]: 	at NametagEdit.jar//com.nametagedit.plugin.NametagEdit.onEnable(NametagEdit.java:40)
[16:39:14] [Server thread/WARN]: 	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264)
[16:39:14] [Server thread/WARN]: 	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:370)
[16:39:14] [Server thread/WARN]: 	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:501)
[16:39:14] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_18_R1.CraftServer.enablePlugin(CraftServer.java:562)
[16:39:14] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_18_R1.CraftServer.enablePlugins(CraftServer.java:476)
[16:39:14] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:736)
[16:39:14] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:503)
[16:39:14] [Server thread/WARN]: 	at net.minecraft.server.dedicated.DedicatedServer.e(DedicatedServer.java:313)
[16:39:14] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:1211)
[16:39:14] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:317)
[16:39:14] [Server thread/WARN]: 	at java.base/java.lang.Thread.run(Thread.java:833)
[16:39:14] [Server thread/WARN]: java.lang.NullPointerException: Cannot invoke "java.lang.Class.newInstance()" because "com.nametagedit.plugin.packets.PacketAccessor.packetClass" is null
[16:39:14] [Server thread/WARN]: 	at NametagEdit.jar//com.nametagedit.plugin.packets.PacketAccessor.createPacket(PacketAccessor.java:123)
[16:39:14] [Server thread/WARN]: 	at NametagEdit.jar//com.nametagedit.plugin.packets.PacketWrapper.<init>(PacketWrapper.java:18)
[16:39:14] [Server thread/WARN]: 	at NametagEdit.jar//com.nametagedit.plugin.NametagEdit.testCompat(NametagEdit.java:90)
[16:39:14] [Server thread/WARN]: 	at NametagEdit.jar//com.nametagedit.plugin.NametagEdit.onEnable(NametagEdit.java:40)
[16:39:14] [Server thread/WARN]: 	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264)
[16:39:14] [Server thread/WARN]: 	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:370)
[16:39:14] [Server thread/WARN]: 	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:501)
[16:39:14] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_18_R1.CraftServer.enablePlugin(CraftServer.java:562)
[16:39:14] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_18_R1.CraftServer.enablePlugins(CraftServer.java:476)
[16:39:14] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:736)
[16:39:14] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:503)
[16:39:14] [Server thread/WARN]: 	at net.minecraft.server.dedicated.DedicatedServer.e(DedicatedServer.java:313)
[16:39:14] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:1211)
[16:39:14] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:317)
[16:39:14] [Server thread/WARN]: 	at java.base/java.lang.Thread.run(Thread.java:833)
[16:39:14] [Server thread/INFO]: [NametagEdit] Disabling NametagEdit v4.4.10
[16:39:14] [Server thread/ERROR]: Error occurred while disabling NametagEdit v4.4.10 (Is it up to date?)
java.lang.NullPointerException: Cannot invoke "com.nametagedit.plugin.NametagManager.reset()" because "this.manager" is null
	at com.nametagedit.plugin.NametagEdit.onDisable(NametagEdit.java:73) ~[NametagEdit.jar:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:266) ~[paper-api-1.18.1-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.plugin.java.JavaPluginLoader.disablePlugin(JavaPluginLoader.java:399) ~[paper-api-1.18.1-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.plugin.SimplePluginManager.disablePlugin(SimplePluginManager.java:538) ~[paper-api-1.18.1-R0.1-SNAPSHOT.jar:?]
	at com.nametagedit.plugin.NametagEdit.testCompat(NametagEdit.java:93) ~[NametagEdit.jar:?]
	at com.nametagedit.plugin.NametagEdit.onEnable(NametagEdit.java:40) ~[NametagEdit.jar:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264) ~[paper-api-1.18.1-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:370) ~[paper-api-1.18.1-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:501) ~[paper-api-1.18.1-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.craftbukkit.v1_18_R1.CraftServer.enablePlugin(CraftServer.java:562) ~[paper-1.18.1.jar:git-Paper-[215](https://aternos.org/log/#L215)]
	at org.bukkit.craftbukkit.v1_18_R1.CraftServer.enablePlugins(CraftServer.java:476) ~[paper-1.18.1.jar:git-Paper-215]
	at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:736) ~[paper-1.18.1.jar:git-Paper-215]
	at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:503) ~[paper-1.18.1.jar:git-Paper-215]
	at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:313) ~[paper-1.18.1.jar:git-Paper-215]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1211) ~[paper-1.18.1.jar:git-Paper-215]
	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:317) ~[paper-1.18.1.jar:git-Paper-215]
	at java.lang.Thread.run(Thread.java:833) ~[?:?]
[16:39:14] [Server thread/ERROR]: [NametagEdit] 
------------------------------------------------------
[WARNING] NametagEdit v4.4.10 Failed to load! [WARNING]
------------------------------------------------------
This might be an issue with reflection. REPORT this:
> Cannot invoke "java.lang.reflect.Constructor.newInstance(Object[])" because "com.nametagedit.plugin.packets.PacketWrapper.ChatComponentText" is null
The plugin will now self destruct.
------------------------------------------------------

**Comment by PedroMPagani** [comment]
Hey, I fixed this and forked it to my github!
https://github.com/PedroMPagani/NametagEdit/blob/master/nametagedit-4.5.0-shaded.jar
-

**Comment by priyam1234-spec** [comment]
thanks!
