### ISSUE TITLE
Not working

### ISSUE THREAD

**Issue by info65** [sgtcaze/NametagEdit#739]
Hi,
NameTagEdit don't working on 1.18.2 server.

error:
 `[21:51:00 INFO]: [NametagEdit] Enabling NametagEdit v4.4.10*

[21:51:00 WARN]: java.lang.ClassNotFoundException: net.minecraft.server.v1_18_R2.PacketPlayOutScoreboardTeam
>
[21:51:00 WARN]: at org.bukkit.plugin.java.PluginClassLoader.loadClass0(PluginClassLoader.java:151)
>
[21:51:00 WARN]: at org.bukkit.plugin.java.PluginClassLoader.loadClass(PluginClassLoader.java:103)
>
[21:51:00 WARN]: at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:520)
>
[21:51:00 WARN]: at java.base/java.lang.Class.forName0(Native Method)
>
[21:51:00 WARN]: at java.base/java.lang.Class.forName(Class.java:375)
>
[21:51:00 WARN]: at NametagEdit.jar//com.nametagedit.plugin.packets.PacketAccessor.<clinit>(PacketAccessor.java:59)
>
[21:51:00 WARN]: at NametagEdit.jar//com.nametagedit.plugin.packets.PacketWrapper.<clinit>(PacketWrapper.java:25)
>
[21:51:00 WARN]: at NametagEdit.jar//com.nametagedit.plugin.NametagEdit.testCompat(NametagEdit.java:90)
>
[21:51:00 WARN]: at NametagEdit.jar//com.nametagedit.plugin.NametagEdit.onEnable(NametagEdit.java:40)
>
[21:51:00 WARN]: at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264)
>
[21:51:00 WARN]: at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:370)
>
[21:51:00 WARN]: at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:501)
>
[21:51:00 WARN]: at org.bukkit.craftbukkit.v1_18_R2.CraftServer.enablePlugin(CraftServer.java:559)
>
[21:51:00 WARN]: at org.bukkit.craftbukkit.v1_18_R2.CraftServer.enablePlugins(CraftServer.java:473)
>
[21:51:00 WARN]: at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:664)
>
[21:51:00 WARN]: at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:431)
>
[21:51:00 WARN]: at net.minecraft.server.dedicated.DedicatedServer.e(DedicatedServer.java:316)
>
[21:51:00 WARN]: at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:1163)
>
[21:51:00 WARN]: at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:315)
>
[21:51:00 WARN]: at java.base/java.lang.Thread.run(Thread.java:833)
>
[21:51:00 WARN]: java.lang.ClassNotFoundException: net.minecraft.server.v1_18_R2.ChatComponentText
>
[21:51:00 WARN]: at org.bukkit.plugin.java.PluginClassLoader.loadClass0(PluginClassLoader.java:151)
>
[21:51:00 WARN]: at org.bukkit.plugin.java.PluginClassLoader.loadClass(PluginClassLoader.java:103)
>
[21:51:00 WARN]: at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:520)
>
[21:51:00 WARN]: at java.base/java.lang.Class.forName0(Native Method)
>
[21:51:00 WARN]: at java.base/java.lang.Class.forName(Class.java:375)
>
[21:51:00 WARN]: at NametagEdit.jar//com.nametagedit.plugin.packets.PacketWrapper.<clinit>(PacketWrapper.java:28)
>
[21:51:00 WARN]: at NametagEdit.jar//com.nametagedit.plugin.NametagEdit.testCompat(NametagEdit.java:90)
>
[21:51:00 WARN]: at NametagEdit.jar//com.nametagedit.plugin.NametagEdit.onEnable(NametagEdit.java:40)
>
[21:51:00 WARN]: at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264)
>
[21:51:00 WARN]: at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:370)
>
[21:51:00 WARN]: at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:501)
>
[21:51:00 WARN]: at org.bukkit.craftbukkit.v1_18_R2.CraftServer.enablePlugin(CraftServer.java:559)
>
[21:51:00 WARN]: at org.bukkit.craftbukkit.v1_18_R2.CraftServer.enablePlugins(CraftServer.java:473)
>
[21:51:00 WARN]: at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:664)
>
[21:51:00 WARN]: at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:431)
>
[21:51:00 WARN]: at net.minecraft.server.dedicated.DedicatedServer.e(DedicatedServer.java:316)
>
[21:51:00 WARN]: at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:1163)
>
[21:51:00 WARN]: at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:315)
>
[21:51:00 WARN]: at java.base/java.lang.Thread.run(Thread.java:833)
>
[21:51:00 WARN]: java.lang.NullPointerException: Cannot invoke "java.lang.Class.newInstance()" because "com.nametagedit.plugin.packets.PacketAccessor.packetClass" is null
>
[21:51:00 WARN]: at NametagEdit.jar//com.nametagedit.plugin.packets.PacketAccessor.createPacket(PacketAccessor.java:123)
>
[21:51:00 WARN]: at NametagEdit.jar//com.nametagedit.plugin.packets.PacketWrapper.<init>(PacketWrapper.java:18)
>
[21:51:00 WARN]: at NametagEdit.jar//com.nametagedit.plugin.NametagEdit.testCompat(NametagEdit.java:90)
>
[21:51:00 WARN]: at NametagEdit.jar//com.nametagedit.plugin.NametagEdit.onEnable(NametagEdit.java:40)
>
[21:51:00 WARN]: at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264)
>
[21:51:00 WARN]: at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:370)
>
[21:51:00 WARN]: at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:501)
>
[21:51:00 WARN]: at org.bukkit.craftbukkit.v1_18_R2.CraftServer.enablePlugin(CraftServer.java:559)
>
[21:51:00 WARN]: at org.bukkit.craftbukkit.v1_18_R2.CraftServer.enablePlugins(CraftServer.java:473)
>
[21:51:00 WARN]: at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:664)
>
[21:51:00 WARN]: at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:431)
>
[21:51:00 WARN]: at net.minecraft.server.dedicated.DedicatedServer.e(DedicatedServer.java:316)
>
[21:51:00 WARN]: at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:1163)
>
[21:51:00 WARN]: at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:315)
>
[21:51:00 WARN]: at java.base/java.lang.Thread.run(Thread.java:833)
>
[21:51:00 INFO]: [NametagEdit] Disabling NametagEdit v4.4.10

[21:51:00 ERROR]: Error occurred while disabling NametagEdit v4.4.10 (Is it up to date?)
java.lang.NullPointerException: Cannot invoke "com.nametagedit.plugin.NametagManager.reset()" because "this.manager" is null
at com.nametagedit.plugin.NametagEdit.onDisable(NametagEdit.java:73) ~[NametagEdit.jar:?]
at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:266) ~[paper-api-1.18.2-R0.1-SNAPSHOT.jar:?]
at org.bukkit.plugin.java.JavaPluginLoader.disablePlugin(JavaPluginLoader.java:399) ~[paper-api-1.18.2-R0.1-SNAPSHOT.jar:?]
at org.bukkit.plugin.SimplePluginManager.disablePlugin(SimplePluginManager.java:538) ~[paper-api-1.18.2-R0.1-SNAPSHOT.jar:?]
at com.nametagedit.plugin.NametagEdit.testCompat(NametagEdit.java:93) ~[NametagEdit.jar:?]
at com.nametagedit.plugin.NametagEdit.onEnable(NametagEdit.java:40) ~[NametagEdit.jar:?]
at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264) ~[paper-api-1.18.2-R0.1-SNAPSHOT.jar:?]
at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:370) ~[paper-api-1.18.2-R0.1-SNAPSHOT.jar:?]
at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:501) ~[paper-api-1.18.2-R0.1-SNAPSHOT.jar:?]
at org.bukkit.craftbukkit.v1_18_R2.CraftServer.enablePlugin(CraftServer.java:559) ~[paper-1.18.2.jar:git-Paper-267]
at org.bukkit.craftbukkit.v1_18_R2.CraftServer.enablePlugins(CraftServer.java:473) ~[paper-1.18.2.jar:git-Paper-267]
at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:664) ~[paper-1.18.2.jar:git-Paper-267]
at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:431) ~[paper-1.18.2.jar:git-Paper-267]
at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:316) ~[paper-1.18.2.jar:git-Paper-267]
at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1163) ~[paper-1.18.2.jar:git-Paper-267]
at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:315) ~[paper-1.18.2.jar:git-Paper-267]
at java.lang.Thread.run(Thread.java:833) ~[?:?]
>
[21:51:00 ERROR]: [NametagEdit]
------------------------------------------------------
[WARNING] NametagEdit v4.4.10 Failed to load! [WARNING]
------------------------------------------------------
This might be an issue with reflection. REPORT this:
Cannot invoke "java.lang.reflect.Constructor.newInstance(Object[])" because "com.nametagedit.plugin.packets.PacketWrapper.ChatComponentText" is null
The plugin will now self destruct.
------------------------------------------------------`

**Comment by JustOneMoreBlock** [comment]
Try https://ci.nametagedit.com/job/NametagEdit-Test/lastSuccessfulBuild/artifact/target/NametagEdit.jar

**Comment by uni0n** [comment]
god damn! that works, thank you sir

**Comment by EvilInsid** [comment]
thank you! fixed me to
