### ISSUE TITLE
MySQL error in ordering of groups

### ISSUE THREAD

**Issue by 3lmack** [sgtcaze/NametagEdit#743]
activate the mysql and when using the /nte order command errors come out and there is no effect when ordering it

[13:20:44] [Craft Scheduler Thread - 2/WARN]: java.sql.SQLException: Column count doesn't match value count at row 1
[13:20:44] [Craft Scheduler Thread - 2/WARN]: 	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:965)
[13:20:44] [Craft Scheduler Thread - 2/WARN]: 	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3973)
[13:20:44] [Craft Scheduler Thread - 2/WARN]: 	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3909)
[13:20:44] [Craft Scheduler Thread - 2/WARN]: 	at com.mysql.jdbc.MysqlIO.sendCommand(MysqlIO.java:2527)
[13:20:44] [Craft Scheduler Thread - 2/WARN]: 	at com.mysql.jdbc.MysqlIO.sqlQueryDirect(MysqlIO.java:2680)
[13:20:44] [Craft Scheduler Thread - 2/WARN]: 	at com.mysql.jdbc.ConnectionImpl.execSQL(ConnectionImpl.java:2484)
[13:20:44] [Craft Scheduler Thread - 2/WARN]: 	at com.mysql.jdbc.PreparedStatement.executeInternal(PreparedStatement.java:1858)
[13:20:44] [Craft Scheduler Thread - 2/WARN]: 	at com.mysql.jdbc.PreparedStatement.execute(PreparedStatement.java:1197)
[13:20:44] [Craft Scheduler Thread - 2/WARN]: 	at com.zaxxer.hikari.pool.ProxyPreparedStatement.execute(ProxyPreparedStatement.java:44)
[13:20:44] [Craft Scheduler Thread - 2/WARN]: 	at com.zaxxer.hikari.pool.HikariProxyPreparedStatement.execute(HikariProxyPreparedStatement.java)
[13:20:44] [Craft Scheduler Thread - 2/WARN]: 	at com.nametagedit.plugin.storage.database.tasks.GroupConfigUpdater.run(GroupConfigUpdater.java:27)
[13:20:44] [Craft Scheduler Thread - 2/WARN]: 	at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftTask.run(CraftTask.java:76)
[13:20:44] [Craft Scheduler Thread - 2/WARN]: 	at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:52)
[13:20:44] [Craft Scheduler Thread - 2/WARN]: 	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
[13:20:44] [Craft Scheduler Thread - 2/WARN]: 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
[13:20:44] [Craft Scheduler Thread - 2/WARN]: 	at java.lang.Thread.run(Unknown Source)

**Comment by Probag586** [comment]
my same error, you have solved
