### ISSUE TITLE
Groups file problem

### ISSUE THREAD

**Issue by xJqlen** [sgtcaze/NametagEdit#75]
I have found an issue or a bug. When I first installed the plugin it worked perfectly fine but once I finished my groups.yml file I got a giant error in the config and the plugin stopped working. The message looked like this

```
--> [12:52:34] [Server thread/INFO]: [NametagEdit] Enabling NametagEdit v4.1.0
[12:52:34] [Server thread/ERROR]: Error occurred while enabling NametagEdit v4.1.0 (Is it up to date?)
java.lang.IllegalArgumentException: Name cannot be null
    at org.apache.commons.lang.Validate.notNull(Validate.java:192) ~[spigot.jar:git-Spigot-db6de12-18fbb24]
    at org.bukkit.permissions.Permission.<init>(Permission.java:55) ~[spigot.jar:git-Spigot-db6de12-18fbb24]
    at org.bukkit.permissions.Permission.<init>(Permission.java:35) ~[spigot.jar:git-Spigot-db6de12-18fbb24]
    at com.nametagedit.plugin.storage.data.GroupData.refresh(GroupData.java:25) ~[?:?]
    at com.nametagedit.plugin.storage.flatfile.FlatFileConfig.loadGroups(FlatFileConfig.java:141) ~[?:?]
    at com.nametagedit.plugin.storage.flatfile.FlatFileConfig.load(FlatFileConfig.java:45) ~[?:?]
    at com.nametagedit.plugin.NametagHandler.<init>(NametagHandler.java:51) ~[?:?]
    at com.nametagedit.plugin.NametagEdit.onEnable(NametagEdit.java:30) ~[?:?]
    at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:321) ~[spigot.jar:git-Spigot-db6de12-18fbb24]
    at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:340) [spigot.jar:git-Spigot-db6de12-18fbb24]
    at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:405) [spigot.jar:git-Spigot-db6de12-18fbb24]
    at org.bukkit.craftbukkit.v1_8_R3.CraftServer.loadPlugin(CraftServer.java:357) [spigot.jar:git-Spigot-db6de12-18fbb24]
    at org.bukkit.craftbukkit.v1_8_R3.CraftServer.enablePlugins(CraftServer.java:317) [spigot.jar:git-Spigot-db6de12-18fbb24]
    at net.minecraft.server.v1_8_R3.MinecraftServer.s(MinecraftServer.java:414) [spigot.jar:git-Spigot-db6de12-18fbb24]
    at net.minecraft.server.v1_8_R3.MinecraftServer.k(MinecraftServer.java:378) [spigot.jar:git-Spigot-db6de12-18fbb24]
    at net.minecraft.server.v1_8_R3.MinecraftServer.a(MinecraftServer.java:333) [spigot.jar:git-Spigot-db6de12-18fbb24]
    at net.minecraft.server.v1_8_R3.DedicatedServer.init(DedicatedServer.java:263) [spigot.jar:git-Spigot-db6de12-18fbb24]
    at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:525) [spigot.jar:git-Spigot-db6de12-18fbb24]
    at java.lang.Thread.run(Unknown 
```

I don't know what to do please help! This affects the players nametag and the tablist!

**Comment by sgtcaze** [comment]
Name is null. Please post your config files for Groups.yml.
