### ISSUE TITLE
Not able to join the server

### ISSUE THREAD

**Issue by WongIong** [sgtcaze/NametagEdit#762]
# Bug Report

**Type /ver NametagEdit and post the output.**
4.5.8

**What version of Bukkit/Spigot/PaperSpigot are you using? Type /ver**
paper 1.16.5

**Please explain your issue. How do you trigger it?**
Error on join

**Are there any errors in the console? Please use: https://pastebin.com**

https://pastebin.com/gHzBpDzh

**Comment by shifhu1234** [comment]
I have the exact same issue! paper 1.16.5, can't join.
xyz lost connection: Internal Exception: io.netty.handler.codec.EncoderException: java.lang.NullPointerException: Cannot invoke "java.lang.Enum.ordinal()" because "oenum" is null

**Comment by Aurelien30000** [comment]
Are you sure NameTagEdit is the source of this issue? _Nothing related to it is mentioned in you logs._ Please try **without** it.

**Comment by teeteeteeteetee** [comment]
i can reproduce the bug which doesnt happen in 4.4.10, also paper 1.16.5

![image](https://user-images.githubusercontent.com/62479501/175496212-0366bccb-a486-4142-babb-a2cf4ebfb262.png)

quick update: the plugin suddenly works after removal and then later on added in after running the server without it

**Comment by WongIong** [comment]
@Aurelien30000 Yes i am sure. after i deleted NTE, i can rejoin the server.

**Comment by Aurelien30000** [comment]
Okok, thanks for your investigation, but we would need details and a specific stacktrace involving NameTagEdit _(if available)_. Also, if you have the courage, I invite you to try to find a simple way to reproduce the problem. I haven't tried yet, but does simple/basic usage _is enough_ to cause the error?

**Comment by WongIong** [comment]
[12:42:07 INFO]: WongIong[/127.0.0.1:7135] logged in with entity id 212 at ([world]-30.705658252799566, 92.3661354490063, -291.21510562930985)
[12:42:08 ERROR]: java.lang.NullPointerException: Cannot invoke "java.lang.Enum.ordinal()" because "oenum" is null
[12:42:08 WARN]: java.lang.NullPointerException: Cannot invoke "java.lang.Enum.ordinal()" because "oenum" is null
[12:42:08 WARN]:        at net.minecraft.server.v1_16_R3.PacketDataSerializer.a(PacketDataSerializer.java:192)
[12:42:08 WARN]:        at net.minecraft.server.v1_16_R3.PacketPlayOutScoreboardTeam.b(PacketPlayOutScoreboardTeam.java:116)
[12:42:08 WARN]:        at net.minecraft.server.v1_16_R3.PacketEncoder.encode(PacketEncoder.java:46)
[12:42:08 WARN]:        at net.minecraft.server.v1_16_R3.PacketEncoder.encode(PacketEncoder.java:15)
[12:42:08 WARN]:        at jdk.internal.reflect.GeneratedMethodAccessor26.invoke(Unknown Source)
[12:42:08 WARN]:        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[12:42:08 WARN]:        at java.base/java.lang.reflect.Method.invoke(Method.java:567)
[12:42:08 WARN]:        at com.comphenix.protocol.injector.netty.ChannelInjector.encode(ChannelInjector.java:531)
[12:42:08 WARN]:        at com.comphenix.protocol.injector.netty.ChannelInjector.access$100(ChannelInjector.java:72)
[12:42:08 WARN]:        at com.comphenix.protocol.injector.netty.ChannelInjector$1.encode(ChannelInjector.java:271)
[12:42:08 WARN]:        at io.netty.handler.codec.MessageToByteEncoder.write(MessageToByteEncoder.java:107)
[12:42:08 WARN]:        at com.comphenix.protocol.injector.netty.ChannelInjector$1.write(ChannelInjector.java:277)
[12:42:08 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:717)
[12:42:08 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.invokeWriteAndFlush(AbstractChannelHandlerContext.java:764)
[12:42:08 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:790)
[12:42:08 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.writeAndFlush(AbstractChannelHandlerContext.java:758)
[12:42:08 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.writeAndFlush(AbstractChannelHandlerContext.java:808)
[12:42:08 WARN]:        at io.netty.channel.DefaultChannelPipeline.writeAndFlush(DefaultChannelPipeline.java:1025)
[12:42:08 WARN]:        at io.netty.channel.AbstractChannel.writeAndFlush(AbstractChannel.java:294)
[12:42:08 WARN]:        at com.comphenix.protocol.injector.netty.ChannelProxy.writeAndFlush(ChannelProxy.java:327)
[12:42:08 WARN]:        at net.minecraft.server.v1_16_R3.NetworkManager.lambda$b$6(NetworkManager.java:323)
[12:42:08 WARN]:        at com.comphenix.protocol.injector.netty.ChannelInjector$3.lambda$onMessageScheduled$1(ChannelInjector.java:354)
[12:42:08 WARN]:        at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:164)
[12:42:08 WARN]:        at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:472)
[12:42:08 WARN]:        at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:500)
[12:42:08 WARN]:        at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989)
[12:42:08 WARN]:        at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
[12:42:08 WARN]:        at java.base/java.lang.Thread.run(Thread.java:831)
[12:42:09 INFO]: WongIong lost connection: Internal Exception: io.netty.handler.codec.EncoderException: java.lang.NullPointerException: Cannot invoke "java.lang.Enum.ordinal()" because "oenum" is null
[12:42:09 INFO]: WongIong left the game


I setup a clean 1.16.5 server and this still happens, so i think it could be really easy to reproduce.

**Comment by Aurelien30000** [comment]
Oh I see! Can you try this version please?
[NametagEdit.zip](https://github.com/sgtcaze/NametagEdit/files/8992995/NametagEdit.zip)

**Comment by Aurelien30000** [comment]
That has been fixed.

**Comment by WongIong** [comment]
oh! thank you :)
