### ISSUE TITLE
SQL Error

### ISSUE THREAD

**Issue by DB-CH** [sgtcaze/NametagEdit#768]
# Bug Report

**Type /ver NametagEdit and post the output.**

[19:00:43 INFO]: NametagEdit version 4.5.8
[19:00:43 INFO]: Authors: sgtcaze, Cory, Lorenzo0111 and Aurelien30000

**What version of Bukkit/Spigot/PaperSpigot are you using? Type /ver**

[19:00:59 INFO]: This server is running Paper version git-Paper-36 (MC: 1.19) (Implementing API version 1.19-R0.1-SNAPSHOT) (Git: 5593f4e)

**What plugins are you using? Type /plugins**

**Please explain your issue. How do you trigger it?**

/ne group order ADMIN OWNER member default

**Are there any errors in the console? Please use: https://pastebin.com**

[18:57:34 INFO]: xxx issued server command: /ne group order ADMIN OWNER member default
[18:57:34 WARN]: java.sql.SQLException: Column count doesn't match value count at row 1
[18:57:34 WARN]:        at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:129)
[18:57:34 WARN]:        at com.mysql.cj.jdbc.exceptions.SQLExceptionsMapping.translateException(SQLExceptionsMapping.java:122)
[18:57:34 WARN]:        at com.mysql.cj.jdbc.ClientPreparedStatement.executeInternal(ClientPreparedStatement.java:916)
[18:57:34 WARN]:        at com.mysql.cj.jdbc.ClientPreparedStatement.execute(ClientPreparedStatement.java:354)
[18:57:34 WARN]:        at NametagEdit.jar//com.zaxxer.hikari.pool.ProxyPreparedStatement.execute(ProxyPreparedStatement.java:44)
[18:57:34 WARN]:        at NametagEdit.jar//com.zaxxer.hikari.pool.HikariProxyPreparedStatement.execute(HikariProxyPreparedStatement.java)
[18:57:34 WARN]:        at NametagEdit.jar//com.nametagedit.plugin.storage.database.tasks.GroupConfigUpdater.run(GroupConfigUpdater.java:27)
[18:57:34 WARN]:        at org.bukkit.craftbukkit.v1_19_R1.scheduler.CraftTask.run(CraftTask.java:101)
[18:57:34 WARN]:        at org.bukkit.craftbukkit.v1_19_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:57)
[18:57:34 WARN]:        at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22)
[18:57:34 WARN]:        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
[18:57:34 WARN]:        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
[18:57:34 WARN]:        at java.base/java.lang.Thread.run(Thread.java:833)

**Comment by Probag586** [comment]
same problem, you have solved?
