### ISSUE TITLE
Nametag is not showing and not working

### ISSUE THREAD

**Issue by Bluejoy2123** [sgtcaze/NametagEdit#776]
# Bug Report

**Type /ver NametagEdit and post the output.**

4.5.8 Version of Nametagedit

**What version of Bukkit/Spigot/PaperSpigot are you using? Type /ver**
Paper 1.18.2

**Please explain your issue. How do you trigger it?**
We couldn't get the Nametag to show even we got the group ready for it.

**What plugins are you using? Type /plugins**

<img width="664" alt="ภาพถ่ายหน้าจอ 2565-07-12 เวลา 00 06 13" src="https://user-images.githubusercontent.com/108882616/178319641-7ad04678-5375-42c0-aa01-24e0ccf06a5a.png">

**Are there any errors in the console? Please use: https://pastebin.com**

[Mon 16:28:48 WARN  NametagEdit] Task #32503 for NametagEdit v4.5.2 generated an exception
java.lang.NullPointerException: Cannot invoke "com.nametagedit.plugin.packets.VersionChecker$BukkitVersion.ordinal()" because the return value of "com.nametagedit.plugin.packets.VersionChecker.getBukkitVersion()" is null
    at NametagEdit.jar//com.nametagedit.plugin.utils.Utils.format(Utils.java:38)
    at NametagEdit.jar//com.nametagedit.plugin.NametagHandler.formatWithPlaceholders(NametagHandler.java:303)
    at NametagEdit.jar//com.nametagedit.plugin.NametagHandler$6.run(NametagHandler.java:391)
    at org.bukkit.craftbukkit.v1_18_R2.scheduler.CraftTask.run(CraftTask.java:101)
    at org.bukkit.craftbukkit.v1_18_R2.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:483)
    at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1532)
    at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:483)
    at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1456)
    at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1226)
    at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:316)
    at java.base/java.lang.Thread.run(Thread.java:833)

**Comment by overkidding** [comment]
Is the problem solved or you're still having the issue?
