### ISSUE TITLE
Latest version causes player disconnection and console spam in 1.16.5

### ISSUE THREAD

**Issue by TheFaik** [sgtcaze/NametagEdit#779]
Latest version causes player disconnection and console spam in 1.16.5

[21:00:57 WARN]: java.lang.NullPointerException [21:00:57 WARN]: at net.minecraft.server.v1_16_R3.PacketDataSerializer.a(PacketDataSerializer.java:192) [21:00:57 WARN]: at net.minecraft.server.v1_16_R3.PacketPlayOutScoreboardTeam.b(PacketPlayOutScoreboardTeam.java:116) [21:00:57 WARN]: at net.minecraft.server.v1_16_R3.PacketEncoder.encode(PacketEncoder.java:46) [21:00:57 WARN]: at net.minecraft.server.v1_16_R3.PacketEncoder.encode(PacketEncoder.java:15)

**Comment by JustOneMoreBlock** [comment]
Pushed an update on Spigot.
