### ISSUE TITLE
1.19.2 Support issue

### ISSUE THREAD

**Issue by TeoSaloufardos** [sgtcaze/NametagEdit#794]
Plugin Version: 4.5.10
Purpur version: 1.19.2

Plugin just doesnt work

**Comment by WongIong** [comment]
[06:36:54 WARN]: [NametagEdit] Plugin NametagEdit v4.5.10 generated an exception while executing task 12187
java.lang.NullPointerException: Cannot invoke "com.nametagedit.plugin.packets.VersionChecker$BukkitVersion.ordinal()" because the return value of "com.nametagedit.plugin.packets.VersionChecker.getBukkitVersion()" is null
        at com.nametagedit.plugin.api.data.FakeTeam.<init>(FakeTeam.java:33) ~[NametagEdit.jar:?]
        at com.nametagedit.plugin.NametagManager.addPlayerToTeam(NametagManager.java:58) ~[NametagEdit.jar:?]
        at com.nametagedit.plugin.NametagManager.setNametag(NametagManager.java:136) ~[NametagEdit.jar:?]
        at com.nametagedit.plugin.NametagManager.setNametag(NametagManager.java:128) ~[NametagEdit.jar:?]
        at com.nametagedit.plugin.api.NametagAPI.showNametag(NametagAPI.java:105) ~[NametagEdit.jar:?]
        at com.nametagedit.plugin.hooks.invisibility.InvisibilityTask.run(InvisibilityTask.java:24) ~[NametagEdit.jar:?]
        at org.bukkit.craftbukkit.v1_19_R1.scheduler.CraftTask.run(CraftTask.java:101) ~[paper-1.19.2.jar:git-Paper-118]
        at org.bukkit.craftbukkit.v1_19_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:57) ~[paper-1.19.2.jar:git-Paper-118]
        at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22) ~[paper-1.19.2.jar:?]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) ~[?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) ~[?:?]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]

**Comment by TeoSaloufardos** [comment]
yes i got this error too

**Comment by JustOneMoreBlock** [comment]
Pushed an update on Spigot.
