### ISSUE TITLE
1.19.3 Support?

### ISSUE THREAD

**Issue by BaxAndrei** [sgtcaze/NametagEdit#823]
# Bug Report

**Type /ver NametagEdit and post the output.**
 NametagEdit v4.5.11

**What version of Bukkit/Spigot/PaperSpigot are you using? Type /ver**
This server is running Paper version git-Paper-333 (MC: 1.19.3) (Implementing API version 1.19.3-R0.1-SNAPSHOT) (Git: eec64a4)

**What plugins are you using? Type /plugins**
It is not relevant in this case.

**Please explain your issue. How do you trigger it?**
I updated to 1.19.3 (the server) and connected to the server.

**Are there any errors in the console? Please use: https://pastebin.com**
```
[14:48:29 WARN]: [NametagEdit] Plugin NametagEdit v4.5.11 generated an exception while executing task 3191
java.lang.NullPointerException: Cannot invoke "com.nametagedit.plugin.packets.VersionChecker$BukkitVersion.ordinal()" because the return value of "com.nametagedit.plugin.packets.VersionChecker.getBukkitVersion()" is null
        at com.nametagedit.plugin.api.data.FakeTeam.<init>(FakeTeam.java:33) ~[NametagEdit.jar:?]
        at com.nametagedit.plugin.NametagManager.addPlayerToTeam(NametagManager.java:58) ~[NametagEdit.jar:?]
        at com.nametagedit.plugin.NametagManager.setNametag(NametagManager.java:136) ~[NametagEdit.jar:?]
        at com.nametagedit.plugin.NametagManager.setNametag(NametagManager.java:128) ~[NametagEdit.jar:?]
        at com.nametagedit.plugin.api.NametagAPI.showNametag(NametagAPI.java:105) ~[NametagEdit.jar:?]
        at com.nametagedit.plugin.hooks.invisibility.InvisibilityTask.run(InvisibilityTask.java:24) ~[NametagEdit.jar:?]
        at org.bukkit.craftbukkit.v1_19_R2.scheduler.CraftTask.run(CraftTask.java:101) ~[paper-1.19.3.jar:git-Paper-333]
        at org.bukkit.craftbukkit.v1_19_R2.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:57) ~[paper-1.19.3.jar:git-Paper-333]
        at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22) ~[paper-1.19.3.jar:?]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) ~[?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) ~[?:?]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]
[14:48:29 INFO]: BaxAndrei lost connection: Disconnected
[14:48:29 INFO]: BaxAndrei left the game
[14:48:29 WARN]: [NametagEdit] Task #3516 for NametagEdit v4.5.11 generated an exception
java.lang.NullPointerException: Cannot invoke "com.nametagedit.plugin.packets.VersionChecker$BukkitVersion.ordinal()" because the return value of "com.nametagedit.plugin.packets.VersionChecker.getBukkitVersion()" is null
        at com.nametagedit.plugin.utils.Utils.format(Utils.java:38) ~[NametagEdit.jar:?]
        at com.nametagedit.plugin.NametagHandler.formatWithPlaceholders(NametagHandler.java:303) ~[NametagEdit.jar:?]
        at com.nametagedit.plugin.NametagHandler$6.run(NametagHandler.java:391) ~[NametagEdit.jar:?]
        at org.bukkit.craftbukkit.v1_19_R2.scheduler.CraftTask.run(CraftTask.java:101) ~[paper-1.19.3.jar:git-Paper-333]
        at org.bukkit.craftbukkit.v1_19_R2.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:483) ~[paper-1.19.3.jar:git-Paper-333]
        at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1473) ~[paper-1.19.3.jar:git-Paper-333]
        at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:440) ~[paper-1.19.3.jar:git-Paper-333]
        at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1397) ~[paper-1.19.3.jar:git-Paper-333]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1173) ~[paper-1.19.3.jar:git-Paper-333]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:316) ~[paper-1.19.3.jar:git-Paper-333]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]

```

**Comment by JustOneMoreBlock** [comment]
Try the test build that I haven't tested yet. https://ci.nametagedit.com/job/NametagEdit-Test/lastSuccessfulBuild/artifact/target/NametagEdit.jar

**Comment by BaxAndrei** [comment]
It works perfectly. Thank you!
